export const jobTitleSuggestions = [
  'Responsable Ressources Humaines',
  'Chargé de Recrutement',
  'Gestionnaire de Paie',
  'Responsable Formation',
  'Assistant RH',
  'Directeur des Ressources Humaines',
  'Ingénieur Minier',
  'Géologue',
  'Chef de Projet Minier',
  'Technicien Mines',
  'Superviseur de Production',
  'Ingénieur Sécurité Mines',
  'Opérateur Engins Lourds',
  'Foreur',
  'Développeur Full Stack',
  'Data Scientist',
  'Chef de Projet IT',
  'Administrateur Système',
  'Ingénieur DevOps',
  'Analyste Business Intelligence',
  'Technicien Informatique',
  'Support IT',
  'Comptable',
  'Auditeur Financier',
  'Contrôleur de Gestion',
  'Chef Comptable',
  'Analyste Financier',
  'Trésorier',
  'Assistant Comptable',
  'Commercial',
  'Responsable Marketing',
  'Chef de Produit',
  'Account Manager',
  'Business Developer',
  'Chargé de Communication',
  'Responsable Ventes',
  'Ingénieur BTP',
  'Chef de Chantier',
  'Conducteur de Travaux',
  'Architecte',
  'Métreur',
  'Technicien BTP',
];

export const companySuggestions = [
  'Barrick Gold Kibali',
  'AngloGold Ashanti',
  'Glencore',
  'Ivanhoe Mines',
  'Banro Corporation',
  'Loncor Resources',
  'Alphamin Resources',
  'Kamoa Copper',
  'Vodacom Congo',
  'Orange RDC',
  'Airtel Congo',
  'Africell',
  'Rawbank',
  'Equity Bank',
  'Ecobank',
  'TMB',
  'BCDC',
  'FBN Bank',
  'Bralima',
  'Bracongo',
  'Marsavco',
  'Pharmakina',
  'Sonas',
  'SNEL',
  'Regideso',
  'Air France',
  'Brussels Airlines',
  'Ethiopian Airlines',
  'Kenya Airways',
  'Total Energies',
  'Chevron',
  'Perenco',
];

export const locationSuggestions = [
  'Conakry',
  'Nzérékoré',
  'Kankan',
  'Kindia',
  'Labé',
  'Boké',
  'Mamou',
  'Faranah',
  'Kissidougou',
  'Guéckédou',
  'Dabola',
  'Pita',
  'Macenta',
  'Kamsar',
  'Fria',
  'Siguiri',
  'Kouroussa',
  'Télimélé',
  'Dubréka',
  'Coyah',
  'Forécariah',
  'Boffa',
  'Dalaba',
  'Mali',
  'Tougué',
  'Koubia',
  'Gaoual',
  'Koundara',
  'Beyla',
  'Yomou',
  'Lola',
  'Dinguiraye',
  'Mandiana',
  'Kérouané',
  'Ratoma',
  'Matoto',
  'Dixinn',
  'Kaloum',
  'Matam',
  'Sangoyah',
  'Sangarédi',
];

export const skillSuggestions = [
  'Microsoft Office',
  'Excel Avancé',
  'PowerPoint',
  'Word',
  'Gestion de Projet',
  'Leadership',
  'Communication',
  'Travail en Équipe',
  'Résolution de Problèmes',
  'Analyse de Données',
  'Gestion du Temps',
  'Négociation',
  'Service Client',
  'Budgétisation',
  'Reporting',
  'Planification Stratégique',
  'JavaScript',
  'Python',
  'React',
  'Node.js',
  'SQL',
  'Java',
  'PHP',
  'Angular',
  'Vue.js',
  'TypeScript',
  'HTML/CSS',
  'Git',
  'Comptabilité Analytique',
  'Consolidation Comptable',
  'Normes IFRS',
  'Audit Interne',
  'Contrôle Budgétaire',
  'Fiscalité',
  'SAP',
  'Oracle',
  'QuickBooks',
  'Sage',
  'Anglais Courant',
  'Français Courant',
  'Lingala',
  'Swahili',
  'Espagnol',
  'Portugais',
  'AutoCAD',
  'CATIA',
  'SolidWorks',
  'Photoshop',
  'Illustrator',
  'Marketing Digital',
  'SEO/SEM',
  'Réseaux Sociaux',
];

export const benefitSuggestions = [
  'Assurance Maladie',
  'Assurance Vie',
  'Véhicule de Fonction',
  'Logement Fourni',
  'Transport Assuré',
  'Tickets Restaurant',
  'Prime de Performance',
  'Prime de Fin d\'Année',
  '13ème Mois',
  '14ème Mois',
  'Congés Payés',
  'Formation Continue',
  'Plan de Carrière',
  'Télétravail Possible',
  'Horaires Flexibles',
  'Ordinateur Portable',
  'Téléphone de Fonction',
  'Abonnement Internet',
  'Salle de Sport',
  'Crèche d\'Entreprise',
  'Restaurant d\'Entreprise',
  'Mutuelle Santé',
  'Retraite Complémentaire',
  'Participation aux Bénéfices',
  'Stock Options',
  'Aide au Logement',
  'Prise en Charge Scolaire',
];

export const languageSuggestions = [
  'Français',
  'Anglais',
  'Arabe',
  'Espagnol',
  'Portugais',
  'Allemand',
  'Mandarin',
  'Japonais',
  'Italien',
  'Russe',
  'Malinké',
  'Soussou',
  'Poular (Peul)',
  'Kissi',
  'Toma',
  'Guerzé (Kpelle)',
  'Konianka',
  'Kono',
  'Lele',
  'Wolof',
];

export const languageLevels = [
  'Débutant (A1)',
  'Élémentaire (A2)',
  'Intermédiaire (B1)',
  'Intermédiaire Avancé (B2)',
  'Avancé (C1)',
  'Maîtrise (C2)',
  'Langue Maternelle',
];

export const sectorSuggestions = [
  'Mines et Ressources Minérales',
  'Pétrole et Gaz',
  'Énergie et Électricité',
  'Énergies Renouvelables',
  'Banque et Finance',
  'Assurance et Réassurance',
  'Microfinance',
  'Technologies de l\'Information',
  'Télécommunications',
  'Cybersécurité',
  'E-commerce et Digital',
  'Construction et BTP',
  'Architecture et Urbanisme',
  'Travaux Publics',
  'Génie Civil',
  'Agriculture et Élevage',
  'Agroalimentaire et Agro-industrie',
  'Pêche et Aquaculture',
  'Sylviculture et Bois',
  'Industrie Manufacturière',
  'Industrie Pharmaceutique',
  'Industrie Textile',
  'Industrie Automobile',
  'Industrie Chimique',
  'Commerce et Distribution',
  'Import-Export',
  'Grande Distribution',
  'Commerce de Gros',
  'Commerce de Détail',
  'Transport et Logistique',
  'Transport Routier',
  'Transport Maritime',
  'Transport Aérien',
  'Fret et Messagerie',
  'Hôtellerie et Restauration',
  'Tourisme et Loisirs',
  'Événementiel',
  'Santé et Médical',
  'Pharmacie',
  'Biotechnologie',
  'Médecine et Soins',
  'Laboratoires d\'Analyse',
  'Éducation et Formation',
  'Enseignement Supérieur',
  'Formation Professionnelle',
  'Recherche et Développement',
  'Médias et Communication',
  'Publicité et Marketing',
  'Audiovisuel et Production',
  'Presse et Édition',
  'Services Professionnels',
  'Conseil et Audit',
  'Juridique et Légal',
  'Expertise Comptable',
  'Ressources Humaines',
  'Recrutement et Intérim',
  'ONG et Développement',
  'Action Humanitaire',
  'Coopération Internationale',
  'Administration Publique',
  'Collectivités Locales',
  'Services Publics',
  'Immobilier et Promotion',
  'Gestion Immobilière',
  'Sécurité et Surveillance',
  'Gardiennage et Sûreté',
  'Sécurité Informatique',
  'Environnement et Écologie',
  'Gestion des Déchets',
  'Eau et Assainissement',
  'Développement Durable',
  'Arts et Culture',
  'Spectacle et Divertissement',
  'Sport et Fitness',
  'Mode et Design',
  'Artisanat',
  'Électronique et High-Tech',
  'Maintenance Industrielle',
  'Mécanique et Métallurgie',
  'Cosmétique et Parfumerie',
  'Luxe et Joaillerie',
  'Avocature et Conseil Juridique',
  'Notariat',
  'Diplomatie et Relations Internationales',
];
