export const jobTitleSuggestions = [
  'Responsable Ressources Humaines',
  'Chargé de Recrutement',
  'Gestionnaire de Paie',
  'Responsable Formation',
  'Assistant RH',
  'Directeur des Ressources Humaines',
  'Ingénieur Minier',
  'Géologue',
  'Chef de Projet Minier',
  'Technicien Mines',
  'Superviseur de Production',
  'Ingénieur Sécurité Mines',
  'Opérateur Engins Lourds',
  'Foreur',
  'Développeur Full Stack',
  'Data Scientist',
  'Chef de Projet IT',
  'Administrateur Système',
  'Ingénieur DevOps',
  'Analyste Business Intelligence',
  'Technicien Informatique',
  'Support IT',
  'Comptable',
  'Auditeur Financier',
  'Contrôleur de Gestion',
  'Chef Comptable',
  'Analyste Financier',
  'Trésorier',
  'Assistant Comptable',
  'Commercial',
  'Responsable Marketing',
  'Chef de Produit',
  'Account Manager',
  'Business Developer',
  'Chargé de Communication',
  'Responsable Ventes',
  'Ingénieur BTP',
  'Chef de Chantier',
  'Conducteur de Travaux',
  'Architecte',
  'Métreur',
  'Technicien BTP',
];

export const companySuggestions = [
  'Barrick Gold Kibali',
  'AngloGold Ashanti',
  'Glencore',
  'Ivanhoe Mines',
  'Banro Corporation',
  'Loncor Resources',
  'Alphamin Resources',
  'Kamoa Copper',
  'Vodacom Congo',
  'Orange RDC',
  'Airtel Congo',
  'Africell',
  'Rawbank',
  'Equity Bank',
  'Ecobank',
  'TMB',
  'BCDC',
  'FBN Bank',
  'Bralima',
  'Bracongo',
  'Marsavco',
  'Pharmakina',
  'Sonas',
  'SNEL',
  'Regideso',
  'Air France',
  'Brussels Airlines',
  'Ethiopian Airlines',
  'Kenya Airways',
  'Total Energies',
  'Chevron',
  'Perenco',
];

export const locationSuggestions = [
  'Kinshasa',
  'Lubumbashi',
  'Goma',
  'Bukavu',
  'Kolwezi',
  'Likasi',
  'Kisangani',
  'Mbuji-Mayi',
  'Kananga',
  'Matadi',
  'Mbandaka',
  'Butembo',
  'Kikwit',
  'Uvira',
  'Beni',
  'Bunia',
  'Kalemie',
  'Gemena',
  'Isiro',
  'Bandundu',
  'Kamsar',
  'Boké',
  'Tshikapa',
  'Gandajika',
];

export const skillSuggestions = [
  'Microsoft Office',
  'Excel Avancé',
  'PowerPoint',
  'Word',
  'Gestion de Projet',
  'Leadership',
  'Communication',
  'Travail en Équipe',
  'Résolution de Problèmes',
  'Analyse de Données',
  'Gestion du Temps',
  'Négociation',
  'Service Client',
  'Budgétisation',
  'Reporting',
  'Planification Stratégique',
  'JavaScript',
  'Python',
  'React',
  'Node.js',
  'SQL',
  'Java',
  'PHP',
  'Angular',
  'Vue.js',
  'TypeScript',
  'HTML/CSS',
  'Git',
  'Comptabilité Analytique',
  'Consolidation Comptable',
  'Normes IFRS',
  'Audit Interne',
  'Contrôle Budgétaire',
  'Fiscalité',
  'SAP',
  'Oracle',
  'QuickBooks',
  'Sage',
  'Anglais Courant',
  'Français Courant',
  'Lingala',
  'Swahili',
  'Espagnol',
  'Portugais',
  'AutoCAD',
  'CATIA',
  'SolidWorks',
  'Photoshop',
  'Illustrator',
  'Marketing Digital',
  'SEO/SEM',
  'Réseaux Sociaux',
];

export const benefitSuggestions = [
  'Assurance Maladie',
  'Assurance Vie',
  'Véhicule de Fonction',
  'Logement Fourni',
  'Transport Assuré',
  'Tickets Restaurant',
  'Prime de Performance',
  'Prime de Fin d\'Année',
  '13ème Mois',
  '14ème Mois',
  'Congés Payés',
  'Formation Continue',
  'Plan de Carrière',
  'Télétravail Possible',
  'Horaires Flexibles',
  'Ordinateur Portable',
  'Téléphone de Fonction',
  'Abonnement Internet',
  'Salle de Sport',
  'Crèche d\'Entreprise',
  'Restaurant d\'Entreprise',
  'Mutuelle Santé',
  'Retraite Complémentaire',
  'Participation aux Bénéfices',
  'Stock Options',
  'Aide au Logement',
  'Prise en Charge Scolaire',
];

export const sectorSuggestions = [
  'Mines',
  'Pétrole et Gaz',
  'Banque et Finance',
  'Télécommunications',
  'Technologies de l\'Information',
  'Commerce et Distribution',
  'Industrie',
  'Agriculture',
  'Construction et BTP',
  'Transport et Logistique',
  'Hôtellerie et Restauration',
  'Santé',
  'Éducation',
  'Énergie',
  'Médias et Communication',
  'Services Professionnels',
  'Conseil et Audit',
  'ONG et Développement',
  'Administration Publique',
  'Immobilier',
  'Assurance',
  'Sécurité',
  'Environnement',
  'Agroalimentaire',
];
