export const jobTitleSuggestions = [
  'Responsable Ressources Humaines',
  'Chargé de Recrutement',
  'Gestionnaire de Paie',
  'Responsable Formation',
  'Assistant RH',
  'Directeur des Ressources Humaines',
  'Ingénieur Minier',
  'Géologue',
  'Chef de Projet Minier',
  'Technicien Mines',
  'Superviseur de Production',
  'Ingénieur Sécurité Mines',
  'Opérateur Engins Lourds',
  'Foreur',
  'Développeur Full Stack',
  'Data Scientist',
  'Chef de Projet IT',
  'Administrateur Système',
  'Ingénieur DevOps',
  'Analyste Business Intelligence',
  'Technicien Informatique',
  'Support IT',
  'Comptable',
  'Auditeur Financier',
  'Contrôleur de Gestion',
  'Chef Comptable',
  'Analyste Financier',
  'Trésorier',
  'Assistant Comptable',
  'Commercial',
  'Responsable Marketing',
  'Chef de Produit',
  'Account Manager',
  'Business Developer',
  'Chargé de Communication',
  'Responsable Ventes',
  'Ingénieur BTP',
  'Chef de Chantier',
  'Conducteur de Travaux',
  'Architecte',
  'Métreur',
  'Technicien BTP',
];

export const companySuggestions = [
  'Barrick Gold Kibali',
  'AngloGold Ashanti',
  'Glencore',
  'Ivanhoe Mines',
  'Banro Corporation',
  'Loncor Resources',
  'Alphamin Resources',
  'Kamoa Copper',
  'Vodacom Congo',
  'Orange RDC',
  'Airtel Congo',
  'Africell',
  'Rawbank',
  'Equity Bank',
  'Ecobank',
  'TMB',
  'BCDC',
  'FBN Bank',
  'Bralima',
  'Bracongo',
  'Marsavco',
  'Pharmakina',
  'Sonas',
  'SNEL',
  'Regideso',
  'Air France',
  'Brussels Airlines',
  'Ethiopian Airlines',
  'Kenya Airways',
  'Total Energies',
  'Chevron',
  'Perenco',
];

export const locationSuggestions = [
  'Conakry',
  'Nzérékoré',
  'Kankan',
  'Kindia',
  'Labé',
  'Boké',
  'Mamou',
  'Faranah',
  'Kissidougou',
  'Guéckédou',
  'Dabola',
  'Pita',
  'Macenta',
  'Kamsar',
  'Fria',
  'Siguiri',
  'Kouroussa',
  'Télimélé',
  'Dubréka',
  'Coyah',
  'Forécariah',
  'Boffa',
  'Dalaba',
  'Mali',
  'Tougué',
  'Koubia',
  'Gaoual',
  'Koundara',
  'Beyla',
  'Yomou',
  'Lola',
  'Dinguiraye',
  'Mandiana',
  'Kérouané',
  'Ratoma',
  'Matoto',
  'Dixinn',
  'Kaloum',
  'Matam',
  'Sangoyah',
  'Sangarédi',
];

export const skillSuggestions = [
  'Microsoft Office',
  'Excel Avancé',
  'PowerPoint',
  'Word',
  'Gestion de Projet',
  'Leadership',
  'Communication',
  'Travail en Équipe',
  'Résolution de Problèmes',
  'Analyse de Données',
  'Gestion du Temps',
  'Négociation',
  'Service Client',
  'Budgétisation',
  'Reporting',
  'Planification Stratégique',
  'JavaScript',
  'Python',
  'React',
  'Node.js',
  'SQL',
  'Java',
  'PHP',
  'Angular',
  'Vue.js',
  'TypeScript',
  'HTML/CSS',
  'Git',
  'Comptabilité Analytique',
  'Consolidation Comptable',
  'Normes IFRS',
  'Audit Interne',
  'Contrôle Budgétaire',
  'Fiscalité',
  'SAP',
  'Oracle',
  'QuickBooks',
  'Sage',
  'Anglais Courant',
  'Français Courant',
  'Lingala',
  'Swahili',
  'Espagnol',
  'Portugais',
  'AutoCAD',
  'CATIA',
  'SolidWorks',
  'Photoshop',
  'Illustrator',
  'Marketing Digital',
  'SEO/SEM',
  'Réseaux Sociaux',
];

export const benefitSuggestions = [
  'Assurance Maladie',
  'Assurance Vie',
  'Véhicule de Fonction',
  'Logement Fourni',
  'Transport Assuré',
  'Tickets Restaurant',
  'Prime de Performance',
  'Prime de Fin d\'Année',
  '13ème Mois',
  '14ème Mois',
  'Congés Payés',
  'Formation Continue',
  'Plan de Carrière',
  'Télétravail Possible',
  'Horaires Flexibles',
  'Ordinateur Portable',
  'Téléphone de Fonction',
  'Abonnement Internet',
  'Salle de Sport',
  'Crèche d\'Entreprise',
  'Restaurant d\'Entreprise',
  'Mutuelle Santé',
  'Retraite Complémentaire',
  'Participation aux Bénéfices',
  'Stock Options',
  'Aide au Logement',
  'Prise en Charge Scolaire',
];

export const languageSuggestions = [
  'Français',
  'Anglais',
  'Arabe',
  'Espagnol',
  'Portugais',
  'Allemand',
  'Mandarin',
  'Japonais',
  'Italien',
  'Russe',
  'Malinké',
  'Soussou',
  'Poular (Peul)',
  'Kissi',
  'Toma',
  'Guerzé (Kpelle)',
  'Konianka',
  'Kono',
  'Lele',
  'Wolof',
];

export const languageLevels = [
  'Débutant (A1)',
  'Élémentaire (A2)',
  'Intermédiaire (B1)',
  'Intermédiaire Avancé (B2)',
  'Avancé (C1)',
  'Maîtrise (C2)',
  'Langue Maternelle',
];

export const sectorSuggestions = [
  'Mines et Ressources Minérales',
  'Extraction de Bauxite',
  'Extraction d\'Or',
  'Extraction de Diamants',
  'Extraction de Fer',
  'Carrières et Exploitation de Pierre',
  'Géologie et Exploration Minière',
  'Pétrole et Gaz',
  'Raffinage Pétrolier',
  'Exploration Pétrolière',
  'Distribution de Carburants',
  'Énergie et Électricité',
  'Production Électrique',
  'Distribution Électrique',
  'Énergies Renouvelables',
  'Énergie Solaire',
  'Énergie Éolienne',
  'Énergie Hydroélectrique',
  'Biomasse et Biogaz',
  'Banque et Finance',
  'Banque Commerciale',
  'Banque d\'Investissement',
  'Banque Islamique',
  'Assurance et Réassurance',
  'Assurance Vie',
  'Assurance IARD',
  'Courtage en Assurance',
  'Microfinance',
  'Crédit Rural',
  'Tontines et Épargne Communautaire',
  'Fintech et Services Financiers',
  'Mobile Money et Paiement Digital',
  'Transfert d\'Argent',
  'Investissement et Capital-risque',
  'Technologies de l\'Information',
  'Développement Logiciel',
  'Développement Web',
  'Développement Mobile',
  'Intelligence Artificielle et Machine Learning',
  'Big Data et Analytics',
  'Data Science',
  'Cloud Computing',
  'Infrastructure Cloud',
  'SaaS et Solutions Cloud',
  'Télécommunications',
  'Opérateurs Télécom',
  'Services Internet',
  'Réseaux et Infrastructure',
  'Fibre Optique',
  'Cybersécurité',
  'Sécurité des Systèmes d\'Information',
  'Audit de Sécurité',
  'E-commerce et Digital',
  'Marketplace en Ligne',
  'Vente en Ligne de Produits',
  'Marketing Digital',
  'SEO et Référencement',
  'Publicité en Ligne',
  'Blockchain et Cryptomonnaie',
  'Construction et BTP',
  'Construction de Bâtiments',
  'Construction Métallique',
  'Préfabrication',
  'Architecture et Urbanisme',
  'Design Architectural',
  'Planification Urbaine',
  'Travaux Publics',
  'Terrassement',
  'Voirie et Réseaux Divers (VRD)',
  'Génie Civil',
  'Structures et Béton',
  'Calcul de Structures',
  'Infrastructures Routières',
  'Construction de Routes',
  'Entretien Routier',
  'Ponts et Ouvrages d\'Art',
  'Barrages et Hydraulique',
  'Agriculture et Élevage',
  'Agriculture Vivrière',
  'Cultures d\'Exportation',
  'Riziculture',
  'Culture Maraîchère',
  'Agroalimentaire et Agro-industrie',
  'Transformation Alimentaire',
  'Conditionnement Agroalimentaire',
  'Meunerie et Transformation de Céréales',
  'Pêche et Aquaculture',
  'Pêche Maritime',
  'Pisciculture',
  'Transformation du Poisson',
  'Sylviculture et Bois',
  'Exploitation Forestière',
  'Scierie et Menuiserie',
  'Ébénisterie',
  'Horticulture et Maraîchage',
  'Floriculture',
  'Pépinières',
  'Élevage Bovin',
  'Élevage Laitier',
  'Élevage de Viande',
  'Aviculture',
  'Élevage de Poulets',
  'Production d\'Œufs',
  'Élevage Porcin',
  'Élevage Ovin et Caprin',
  'Apiculture',
  'Sériciculture',
  'Industrie Manufacturière',
  'Assemblage et Production',
  'Usinage',
  'Industrie Pharmaceutique',
  'Production de Médicaments',
  'Pharmacovigilance',
  'Distribution Pharmaceutique',
  'Industrie Textile',
  'Tissage et Filature',
  'Confection Textile',
  'Teinturerie',
  'Industrie Automobile',
  'Assemblage Automobile',
  'Pièces Détachées Auto',
  'Garages et Mécanique Auto',
  'Industrie Chimique',
  'Chimie de Base',
  'Peintures et Vernis',
  'Détergents et Savons',
  'Industrie Alimentaire',
  'Boulangerie Industrielle',
  'Brasserie et Boissons',
  'Laiterie et Produits Laitiers',
  'Huilerie',
  'Confiserie et Chocolaterie',
  'Emballage et Conditionnement',
  'Production d\'Emballages',
  'Cartonnerie',
  'Commerce et Distribution',
  'Commerce Général',
  'Négoce International',
  'Import-Export',
  'Sourcing et Approvisionnement',
  'Courtage Commercial',
  'Grande Distribution',
  'Supermarchés et Hypermarchés',
  'Commerce de Proximité',
  'Commerce de Gros',
  'Grossiste Alimentaire',
  'Grossiste Non-Alimentaire',
  'Commerce de Détail',
  'Boutiques Spécialisées',
  'Kiosques et Petits Commerces',
  'Vente en Ligne',
  'E-commerce Local',
  'Dropshipping',
  'Transport et Logistique',
  'Transport de Marchandises',
  'Transport de Personnes',
  'Transport Routier',
  'Transport par Camions',
  'Transport Urbain',
  'Transport Maritime',
  'Transport Fluvial',
  'Services Portuaires',
  'Transport Aérien',
  'Compagnies Aériennes',
  'Services Aéroportuaires',
  'Transport Ferroviaire',
  'Fret et Messagerie',
  'Coursiers et Livraison',
  'Messagerie Express',
  'Supply Chain et Achats',
  'Gestion des Stocks',
  'Planification Logistique',
  'Entreposage et Stockage',
  'Gestion d\'Entrepôts',
  'Stockage Frigorifique',
  'Hôtellerie et Restauration',
  'Hôtellerie de Luxe',
  'Hôtels d\'Affaires',
  'Auberges et Pensions',
  'Restaurants Gastronomiques',
  'Restauration Rapide',
  'Cafés et Salons de Thé',
  'Tourisme et Loisirs',
  'Écotourisme',
  'Tourisme d\'Affaires',
  'Parcs et Attractions',
  'Agences de Voyage',
  'Tour Operators',
  'Guides Touristiques',
  'Événementiel',
  'Organisation d\'Événements',
  'Salons et Foires',
  'Mariages et Cérémonies',
  'Catering et Traiteur',
  'Service Traiteur',
  'Banquets et Réceptions',
  'Santé et Médical',
  'Hôpitaux et Cliniques',
  'Centres de Santé',
  'Soins à Domicile',
  'Pharmacie',
  'Officines',
  'Parapharmacie',
  'Biotechnologie',
  'Recherche Biomédicale',
  'Génétique',
  'Médecine et Soins',
  'Médecine Générale',
  'Médecine Spécialisée',
  'Chirurgie',
  'Dentaire et Orthodontie',
  'Soins Dentaires',
  'Prothèses Dentaires',
  'Ophtalmologie',
  'Soins Oculaires',
  'Optométrie',
  'Radiologie et Imagerie',
  'Scanner et IRM',
  'Échographie',
  'Laboratoires d\'Analyse',
  'Analyses Médicales',
  'Biologie Clinique',
  'Équipements Médicaux',
  'Distribution Matériel Médical',
  'Maintenance Équipements Médicaux',
  'Éducation et Formation',
  'Écoles Privées',
  'Centres de Formation',
  'Enseignement Supérieur',
  'Universités',
  'Grandes Écoles',
  'Enseignement Primaire et Secondaire',
  'Écoles Primaires',
  'Collèges et Lycées',
  'Formation Professionnelle',
  'Apprentissage et Alternance',
  'Formation Continue',
  'Formation à Distance et E-learning',
  'Cours en Ligne',
  'Plateformes Éducatives',
  'Recherche et Développement',
  'Laboratoires de Recherche',
  'Innovation et R&D',
  'Médias et Communication',
  'Télévision',
  'Radio',
  'Presse Écrite',
  'Publicité et Marketing',
  'Agences Publicitaires',
  'Marketing Stratégique',
  'Relations Publiques',
  'Communication Corporate',
  'Gestion de Crise',
  'Audiovisuel et Production',
  'Production Vidéo',
  'Studios d\'Enregistrement',
  'Post-production',
  'Presse et Édition',
  'Maisons d\'Édition',
  'Journalisme',
  'Réseaux Sociaux et Community Management',
  'Gestion des Réseaux Sociaux',
  'Influence Marketing',
  'Services Professionnels',
  'Services aux Entreprises',
  'Conseil en Organisation',
  'Conseil et Audit',
  'Audit Financier',
  'Audit Opérationnel',
  'Conseil en Management',
  'Change Management',
  'Optimisation des Processus',
  'Conseil en Stratégie',
  'Stratégie d\'Entreprise',
  'Développement Commercial',
  'Juridique et Légal',
  'Cabinets d\'Avocats',
  'Contentieux',
  'Expertise Comptable',
  'Comptabilité Générale',
  'Commissariat aux Comptes',
  'Fiscalité',
  'Conseil Fiscal',
  'Optimisation Fiscale',
  'Ressources Humaines',
  'Gestion RH',
  'Formation RH',
  'Recrutement et Intérim',
  'Chasse de Têtes',
  'Agences de Recrutement',
  'Gestion des Talents',
  'Développement des Compétences',
  'Évaluation du Personnel',
  'Paie et Administration du Personnel',
  'Gestion de la Paie',
  'Administration RH',
  'ONG et Développement',
  'Aide au Développement',
  'Projets Communautaires',
  'Action Humanitaire',
  'Aide d\'Urgence',
  'Programmes Humanitaires',
  'Coopération Internationale',
  'Partenariats Internationaux',
  'Aide Bilatérale',
  'Développement Communautaire',
  'Animation Sociale',
  'Développement Local',
  'Microprojet et Entrepreneuriat Social',
  'Accompagnement d\'Entrepreneurs',
  'Économie Sociale et Solidaire',
  'Administration Publique',
  'Ministères et Institutions',
  'Services Administratifs',
  'Collectivités Locales',
  'Mairies et Communes',
  'Préfectures et Sous-préfectures',
  'Services Publics',
  'Services à la Population',
  'Services Techniques',
  'Fonction Publique',
  'Administration Centrale',
  'Fonction Publique Territoriale',
  'Immobilier et Promotion',
  'Promotion Immobilière Résidentielle',
  'Immobilier Commercial',
  'Gestion Immobilière',
  'Administration de Biens',
  'Location Immobilière',
  'Promotion Immobilière',
  'Lotissements',
  'Aménagement Foncier',
  'Syndic et Copropriété',
  'Gestion de Copropriété',
  'Syndic Professionnel',
  'Sécurité et Surveillance',
  'Sociétés de Sécurité',
  'Sécurité Rapprochée',
  'Gardiennage et Sûreté',
  'Gardiennage de Sites',
  'Rondes de Sécurité',
  'Sécurité Informatique',
  'Protection des Données',
  'Cyberdéfense',
  'Sécurité Incendie',
  'Prévention Incendie',
  'Systèmes Anti-incendie',
  'Environnement et Écologie',
  'Protection de l\'Environnement',
  'Conservation de la Nature',
  'Gestion des Déchets',
  'Collecte des Déchets',
  'Traitement des Déchets',
  'Recyclage',
  'Valorisation des Déchets',
  'Économie Circulaire',
  'Eau et Assainissement',
  'Distribution d\'Eau Potable',
  'Traitement des Eaux',
  'Assainissement Urbain',
  'Développement Durable',
  'RSE et Développement Durable',
  'Transition Écologique',
  'Énergies Propres',
  'Efficacité Énergétique',
  'Technologies Propres',
  'Arts et Culture',
  'Arts Plastiques',
  'Galeries d\'Art',
  'Musées et Patrimoine',
  'Conservation du Patrimoine',
  'Musées Nationaux',
  'Spectacle et Divertissement',
  'Arts de la Scène',
  'Théâtre',
  'Cinéma et Production Audiovisuelle',
  'Production Cinématographique',
  'Distribution de Films',
  'Musique et Son',
  'Production Musicale',
  'Édition Musicale',
  'Sport et Fitness',
  'Salles de Sport',
  'Équipements Sportifs',
  'Clubs Sportifs',
  'Fédérations Sportives',
  'Associations Sportives',
  'Coaching Sportif',
  'Préparation Physique',
  'Entraînement Personnel',
  'Mode et Design',
  'Création de Mode',
  'Stylisme',
  'Design Graphique',
  'Identité Visuelle',
  'Communication Visuelle',
  'Design d\'Intérieur',
  'Décoration Intérieure',
  'Aménagement d\'Espaces',
  'Artisanat',
  'Artisanat d\'Art',
  'Vannerie',
  'Poterie et Céramique',
  'Sculpture',
  'Bijouterie et Orfèvrerie',
  'Joaillerie',
  'Création de Bijoux',
  'Électronique et High-Tech',
  'Électronique Grand Public',
  'Systèmes Électroniques',
  'Électroménager',
  'Appareils Ménagers',
  'Réparation Électroménager',
  'Maintenance Industrielle',
  'Maintenance Préventive',
  'Maintenance Corrective',
  'Mécanique et Métallurgie',
  'Mécanique Générale',
  'Chaudronnerie',
  'Soudure et Chaudronnerie',
  'Soudure Spécialisée',
  'Tuyauterie Industrielle',
  'Cosmétique et Parfumerie',
  'Fabrication de Cosmétiques',
  'Distribution de Produits de Beauté',
  'Beauté et Esthétique',
  'Instituts de Beauté',
  'Soins Esthétiques',
  'Coiffure',
  'Spa et Bien-être',
  'Centres de Spa',
  'Thalassothérapie',
  'Massages et Relaxation',
  'Luxe et Joaillerie',
  'Articles de Luxe',
  'Maroquinerie de Luxe',
  'Horlogerie',
  'Montres de Luxe',
  'Réparation Horlogère',
  'Avocature et Conseil Juridique',
  'Droit des Affaires',
  'Droit Pénal',
  'Droit Civil',
  'Notariat',
  'Actes Notariés',
  'Transactions Immobilières',
  'Huissier de Justice',
  'Exécution des Décisions',
  'Constats',
  'Diplomatie et Relations Internationales',
  'Ambassades et Consulats',
  'Relations Diplomatiques',
  'Organisations Internationales',
  'Agences ONU',
  'Institutions Internationales',
  'Statistiques et Recensement',
  'Études Statistiques',
  'Recensement de Population',
  'Urbanisme et Aménagement du Territoire',
  'Planification Territoriale',
  'Schémas Directeurs',
  'Cartographie et Géomatique',
  'SIG et Cartographie',
  'Topographie',
  'Télédétection',
  'Météorologie et Climatologie',
  'Prévisions Météorologiques',
  'Études Climatiques',
  'Vétérinaire et Soins Animaliers',
  'Cliniques Vétérinaires',
  'Santé Animale',
  'Zootechnie',
  'Assurance Qualité et Contrôle',
  'Contrôle Qualité',
  'Normes et Certification',
  'Traduction et Interprétariat',
  'Services de Traduction',
  'Interprétation de Conférence',
  'Localisation',
  'Impression et Reprographie',
  'Imprimeries',
  'Sérigraphie',
  'Reprographie et Photocopie',
  'Alimentation et Restauration Collective',
  'Cantines Scolaires',
  'Restauration d\'Entreprise',
  'Nettoyage et Services d\'Entretien',
  'Nettoyage Industriel',
  'Services de Propreté',
  'Location et Leasing',
  'Location de Véhicules',
  'Location d\'Équipements',
  'Leasing Financier',
  'Céramique et Matériaux de Construction',
  'Fabrication de Briques',
  'Carrelage et Faïence',
  'Cimenterie',
  'Caoutchouc et Pneumatiques',
  'Plantation de Caoutchouc',
  'Transformation du Caoutchouc',
  'Cacao et Café',
  'Culture du Cacao',
  'Transformation du Café',
  'Export de Produits Tropicaux',
  'Tabac',
  'Culture du Tabac',
  'Transformation du Tabac',
  'Coton',
  'Culture Cotonnière',
  'Égrenage et Transformation',
  'Industrie Cotonnière',
];
