export const sampleFormations = [
  {
    id: 'form-1',
    title: 'Formation Complète en Gestion des Ressources Humaines',
    description: 'Maîtrisez les fondamentaux de la GRH moderne : recrutement, gestion des talents, relations sociales, et droit du travail guinéen.',
    category: 'RH & Management',
    level: 'Débutant à Intermédiaire',
    duration: '3 mois',
    format: 'En ligne + Présentiel',
    price: 2500000,
    instructor: 'Dr. Mamadou Sow',
    instructor_bio: '15 ans d\'expérience en GRH, Ancien DRH de grandes entreprises minières',
    trainer_phone: '622123456',
    trainer_contact_name: 'Dr. Mamadou Sow',
    trainer_email: 'mamadou.sow@formations-grh.gn',
    image: 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=800',
    rating: 4.8,
    students: 156,
    modules: [
      'Fondamentaux de la GRH',
      'Recrutement et sélection',
      'Gestion des talents',
      'Droit du travail guinéen',
      'Relations sociales',
      'Évaluation de la performance',
    ],
    benefits: [
      'Certificat reconnu',
      'Accompagnement personnalisé',
      'Accès à vie aux ressources',
      'Networking professionnel',
    ],
    startDate: '15 Janvier 2025',
    available: true,
  },
  {
    id: 'form-2',
    title: 'Coaching Carrière et Leadership pour Managers',
    description: 'Programme intensif pour développer vos compétences en leadership, management d\'équipe et gestion de carrière.',
    category: 'Leadership & Coaching',
    level: 'Intermédiaire à Avancé',
    duration: '6 semaines',
    format: 'Coaching individuel',
    price: 3500000,
    instructor: 'Fatoumata Diallo',
    instructor_bio: 'Coach Certifiée ICF, Executive Coach pour cadres dirigeants',
    trainer_phone: '622234567',
    trainer_contact_name: 'Fatoumata Diallo',
    trainer_email: 'fatoumata.diallo@coaching-pro.gn',
    image: 'https://images.pexels.com/photos/5257268/pexels-photo-5257268.jpeg?auto=compress&cs=tinysrgb&w=800',
    rating: 4.9,
    students: 89,
    modules: [
      'Leadership transformationnel',
      'Intelligence émotionnelle',
      'Communication efficace',
      'Gestion des conflits',
      'Développement personnel',
      'Plan de carrière stratégique',
    ],
    benefits: [
      '6 sessions de coaching privé',
      'Bilan de compétences',
      'Plan d\'action personnalisé',
      'Suivi post-formation 3 mois',
    ],
    startDate: 'Sessions flexibles',
    available: true,
  },
  {
    id: 'form-3',
    title: 'Formation Hygiène Sécurité Environnement (HSE) Niveau 1',
    description: 'Formation certifiante pour devenir responsable HSE dans les secteurs minier, industriel et BTP en Guinée.',
    category: 'HSE & Sécurité',
    level: 'Débutant',
    duration: '4 semaines',
    format: 'Présentiel',
    price: 1800000,
    instructor: 'Ibrahima Konaté',
    instructor_bio: 'Ingénieur HSE Senior, 12 ans dans le secteur minier',
    trainer_phone: '622345678',
    trainer_contact_name: 'Ibrahima Konaté',
    trainer_email: 'ibrahima.konate@hse-guinee.gn',
    image: 'https://images.pexels.com/photos/3862130/pexels-photo-3862130.jpeg?auto=compress&cs=tinysrgb&w=800',
    rating: 4.7,
    students: 203,
    modules: [
      'Réglementation HSE en Guinée',
      'Identification des risques',
      'Prévention des accidents',
      'Gestion des urgences',
      'Audit et inspection',
      'Culture sécurité',
    ],
    benefits: [
      'Certification HSE Niveau 1',
      'Stage pratique en entreprise',
      'Kit de matériel HSE',
      'Réseau professionnel HSE',
    ],
    startDate: '1er Février 2025',
    available: true,
  },
  {
    id: 'form-4',
    title: 'Bootcamp Développeur Web Full Stack',
    description: 'Devenez développeur web professionnel en 12 semaines : HTML, CSS, JavaScript, React, Node.js, bases de données.',
    category: 'IT & Digital',
    level: 'Débutant',
    duration: '12 semaines',
    format: 'Présentiel intensif',
    price: 4000000,
    instructor: 'Alpha Condé',
    instructor_bio: 'Lead Developer, Formateur tech avec +100 développeurs formés',
    trainer_phone: '622456789',
    trainer_contact_name: 'Alpha Condé',
    trainer_email: 'alpha.conde@webdev-academy.gn',
    image: 'https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=800',
    rating: 4.9,
    students: 127,
    modules: [
      'Fondamentaux Web (HTML/CSS/JS)',
      'React et composants modernes',
      'Backend avec Node.js',
      'Bases de données SQL/NoSQL',
      'APIs REST et GraphQL',
      'Déploiement et DevOps',
    ],
    benefits: [
      'Projets réels en portfolio',
      'Aide au placement en entreprise',
      'Mentorat 1-on-1',
      'Accès communauté alumni',
    ],
    startDate: '20 Janvier 2025',
    available: true,
  },
  {
    id: 'form-5',
    title: 'Formation Marketing Digital et Réseaux Sociaux',
    description: 'Maîtrisez le marketing digital, SEO, publicité en ligne et community management pour booster votre business.',
    category: 'Marketing & Communication',
    level: 'Débutant à Intermédiaire',
    duration: '6 semaines',
    format: 'Hybride (50% en ligne)',
    price: 2000000,
    instructor: 'Hadja Bah',
    instructor_bio: 'Digital Strategist, Consultante pour PME et startups',
    trainer_phone: '622567890',
    trainer_contact_name: 'Hadja Bah',
    trainer_email: 'hadja.bah@digital-marketing.gn',
    image: 'https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=800',
    rating: 4.6,
    students: 245,
    modules: [
      'Stratégie marketing digital',
      'SEO et référencement',
      'Publicité Facebook/Instagram',
      'Google Ads et Analytics',
      'Content marketing',
      'Community management',
    ],
    benefits: [
      'Certificat Google Digital',
      'Création campagne réelle',
      'Outils marketing inclus',
      'Support continu 6 mois',
    ],
    startDate: '10 Février 2025',
    available: true,
  },
  {
    id: 'form-6',
    title: 'Gestion de Projet PMP - Préparation Certification',
    description: 'Programme complet pour obtenir la certification PMP et maîtriser les meilleures pratiques en gestion de projet.',
    category: 'Gestion de Projet',
    level: 'Avancé',
    duration: '8 semaines',
    format: 'En ligne',
    price: 3000000,
    instructor: 'Mohamed Keita',
    instructor_bio: 'PMP, PMI-ACP, 20+ ans en gestion de projets complexes',
    trainer_phone: '622678901',
    trainer_contact_name: 'Mohamed Keita',
    trainer_email: 'mohamed.keita@pmp-training.gn',
    image: 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=800',
    rating: 4.8,
    students: 98,
    modules: [
      'Méthodologie PMI',
      '10 domaines de connaissance',
      'Processus et outils PMBOK',
      'Gestion des risques',
      'Agile et Scrum',
      'Préparation examen PMP',
    ],
    benefits: [
      'Simulateurs d\'examen',
      'Support jusqu\'à certification',
      'Matériel d\'étude complet',
      'Garantie réussite',
    ],
    startDate: '5 Janvier 2025',
    available: true,
  },
];

export const formationCategories = [
  { id: 'all', name: 'Toutes les formations', icon: '📚' },
  { id: 'RH & Management', name: 'RH & Management', icon: '👥' },
  { id: 'Leadership & Coaching', name: 'Leadership & Coaching', icon: '🎯' },
  { id: 'HSE & Sécurité', name: 'HSE & Sécurité', icon: '🦺' },
  { id: 'IT & Digital', name: 'IT & Digital', icon: '💻' },
  { id: 'Marketing & Communication', name: 'Marketing', icon: '📢' },
  { id: 'Gestion de Projet', name: 'Gestion de Projet', icon: '📊' },
];
