export const sampleJobs = [
  {
    id: 'sample-1',
    title: 'Ingénieur Génie Civil - Projets Miniers',
    description: 'Nous recherchons un ingénieur civil expérimenté pour superviser nos projets d\'infrastructure minière.',
    location: 'Conakry, Guinée',
    contract_type: 'CDI',
    department: 'Ingénierie',
    status: 'published',
    experience_level: 'Senior',
    salary_min: 15000000,
    salary_max: 25000000,
    company_id: 'sample',
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    applications_count: 24,
    views_count: 156,
    ai_generated: false,
  },
  {
    id: 'sample-2',
    title: 'Responsable HSE - Secteur Minier',
    description: 'Poste stratégique pour assurer la sécurité et la conformité environnementale de nos opérations.',
    location: 'Kamsar, Guinée',
    contract_type: 'CDI',
    department: 'Sécurité & Environnement',
    status: 'published',
    experience_level: 'Senior',
    salary_min: 12000000,
    salary_max: 18000000,
    company_id: 'sample',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    applications_count: 18,
    views_count: 98,
    ai_generated: false,
  },
  {
    id: 'sample-3',
    title: 'Chef de Projet Digital Marketing',
    description: 'Pilotez notre transformation digitale et développez notre présence en ligne.',
    location: 'Conakry, Guinée',
    contract_type: 'CDI',
    department: 'Marketing',
    status: 'published',
    experience_level: 'Intermédiaire',
    salary_min: 8000000,
    salary_max: 12000000,
    company_id: 'sample',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    applications_count: 31,
    views_count: 203,
    ai_generated: true,
  },
  {
    id: 'sample-4',
    title: 'Développeur Full Stack React/Node',
    description: 'Rejoignez notre équipe tech pour construire des solutions innovantes.',
    location: 'Conakry, Guinée (Télétravail possible)',
    contract_type: 'CDD',
    department: 'IT',
    status: 'draft',
    experience_level: 'Junior',
    salary_min: 6000000,
    salary_max: 9000000,
    company_id: 'sample',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    applications_count: 0,
    views_count: 0,
    ai_generated: true,
  },
];

export const sampleApplications = [
  {
    id: 'app-1',
    job_id: 'sample-1',
    candidate_id: 'cand-1',
    ai_score: 94,
    ai_category: 'strong',
    workflow_stage: 'Candidature reçue',
    applied_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    status: 'pending',
    cover_letter: 'Ingénieur civil avec 8 ans d\'expérience dans le secteur minier guinéen...',
    candidate: {
      id: 'cand-1',
      title: 'Ingénieur Civil Senior',
      experience_years: 8,
      education_level: 'Master',
      skills: ['AutoCAD', 'Gestion de projet', 'BTP', 'Normes ISO'],
      profile: {
        full_name: 'Mamadou Diallo',
        email: 'mamadou.diallo@example.gn',
        phone: '+224 621 23 45 67',
        avatar_url: 'https://i.pravatar.cc/150?img=12',
      },
    },
  },
  {
    id: 'app-2',
    job_id: 'sample-1',
    candidate_id: 'cand-2',
    ai_score: 88,
    ai_category: 'strong',
    workflow_stage: 'En évaluation',
    applied_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    status: 'reviewing',
    cover_letter: 'Passionnée par les infrastructures et le développement durable...',
    candidate: {
      id: 'cand-2',
      title: 'Ingénieur Génie Civil',
      experience_years: 6,
      education_level: 'Master',
      skills: ['Calcul de structures', 'Management', 'Revit', 'Contrôle qualité'],
      profile: {
        full_name: 'Fatoumata Camara',
        email: 'fatoumata.camara@example.gn',
        phone: '+224 622 34 56 78',
        avatar_url: 'https://i.pravatar.cc/150?img=5',
      },
    },
  },
  {
    id: 'app-3',
    job_id: 'sample-2',
    candidate_id: 'cand-3',
    ai_score: 91,
    ai_category: 'strong',
    workflow_stage: 'Entretien planifié',
    applied_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    status: 'interview',
    cover_letter: 'Expert HSE avec certifications internationales...',
    candidate: {
      id: 'cand-3',
      title: 'Responsable HSE Senior',
      experience_years: 10,
      education_level: 'Master',
      skills: ['ISO 45001', 'Audit sécurité', 'Formation', 'Gestion de crise'],
      profile: {
        full_name: 'Ibrahima Bah',
        email: 'ibrahima.bah@example.gn',
        phone: '+224 623 45 67 89',
        avatar_url: 'https://i.pravatar.cc/150?img=33',
      },
    },
  },
  {
    id: 'app-4',
    job_id: 'sample-2',
    candidate_id: 'cand-4',
    ai_score: 73,
    ai_category: 'medium',
    workflow_stage: 'Candidature reçue',
    applied_at: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    status: 'pending',
    cover_letter: 'Diplômé en HSE, motivé pour développer mes compétences...',
    candidate: {
      id: 'cand-4',
      title: 'Technicien HSE',
      experience_years: 3,
      education_level: 'Licence',
      skills: ['Prévention', 'Enquêtes accidents', 'Sensibilisation', 'Rapport'],
      profile: {
        full_name: 'Aminata Soumah',
        email: 'aminata.soumah@example.gn',
        phone: '+224 624 56 78 90',
        avatar_url: 'https://i.pravatar.cc/150?img=9',
      },
    },
  },
  {
    id: 'app-5',
    job_id: 'sample-3',
    candidate_id: 'cand-5',
    ai_score: 85,
    ai_category: 'strong',
    workflow_stage: 'Offre envoyée',
    applied_at: new Date(Date.now() - 15 * 60 * 60 * 1000).toISOString(),
    status: 'offer',
    cover_letter: 'Expert en marketing digital avec succès démontrés...',
    candidate: {
      id: 'cand-5',
      title: 'Digital Marketing Manager',
      experience_years: 5,
      education_level: 'Master',
      skills: ['SEO/SEM', 'Social Media', 'Google Ads', 'Analytics', 'Content Strategy'],
      profile: {
        full_name: 'Mohamed Sylla',
        email: 'mohamed.sylla@example.gn',
        phone: '+224 625 67 89 01',
        avatar_url: 'https://i.pravatar.cc/150?img=52',
      },
    },
  },
  {
    id: 'app-6',
    job_id: 'sample-3',
    candidate_id: 'cand-6',
    ai_score: 68,
    ai_category: 'medium',
    workflow_stage: 'En évaluation',
    applied_at: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    status: 'reviewing',
    cover_letter: 'Créatif et passionné par le digital...',
    candidate: {
      id: 'cand-6',
      title: 'Chef de Projet Marketing',
      experience_years: 3,
      education_level: 'Licence',
      skills: ['Facebook Ads', 'Instagram', 'Création contenu', 'Community Management'],
      profile: {
        full_name: 'Hadja Kaba',
        email: 'hadja.kaba@example.gn',
        phone: '+224 626 78 90 12',
        avatar_url: 'https://i.pravatar.cc/150?img=20',
      },
    },
  },
  {
    id: 'app-7',
    job_id: 'sample-3',
    candidate_id: 'cand-7',
    ai_score: 55,
    ai_category: 'weak',
    workflow_stage: 'Candidature reçue',
    applied_at: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    status: 'pending',
    cover_letter: 'Jeune diplômé recherchant opportunité dans le marketing...',
    candidate: {
      id: 'cand-7',
      title: 'Assistant Marketing',
      experience_years: 1,
      education_level: 'BTS',
      skills: ['Réseaux sociaux', 'Bureautique', 'Communication'],
      profile: {
        full_name: 'Alpha Condé',
        email: 'alpha.conde@example.gn',
        phone: '+224 627 89 01 23',
        avatar_url: 'https://i.pravatar.cc/150?img=68',
      },
    },
  },
];

export const sampleWorkflowStages = [
  {
    id: 'stage-1',
    stage_name: 'Candidature reçue',
    stage_order: 1,
    stage_color: '#3B82F6',
    is_default: true,
  },
  {
    id: 'stage-2',
    stage_name: 'En évaluation',
    stage_order: 2,
    stage_color: '#F59E0B',
    is_default: true,
  },
  {
    id: 'stage-3',
    stage_name: 'Entretien planifié',
    stage_order: 3,
    stage_color: '#8B5CF6',
    is_default: true,
  },
  {
    id: 'stage-4',
    stage_name: 'Offre envoyée',
    stage_order: 4,
    stage_color: '#10B981',
    is_default: true,
  },
  {
    id: 'stage-5',
    stage_name: 'Acceptée',
    stage_order: 5,
    stage_color: '#059669',
    is_default: true,
  },
  {
    id: 'stage-6',
    stage_name: 'Refusée',
    stage_order: 6,
    stage_color: '#EF4444',
    is_default: true,
  },
];
