export const sampleBlogPosts = [
  {
    id: 'blog-1',
    title: 'Guide Complet du Recrutement en Guinée en 2025',
    slug: 'guide-recrutement-guinee-2025',
    excerpt: 'Tout ce que vous devez savoir sur le recrutement en Guinée : tendances, meilleures pratiques, aspects légaux et conseils d\'experts.',
    content: `Le marché de l'emploi guinéen connaît une transformation profonde en 2025. Entre digitalisation, nouvelles attentes des candidats et évolutions réglementaires, recruter efficacement demande une approche modernisée...`,
    category: 'Recrutement',
    author: 'Dr. Mamadou Sow',
    authorRole: 'Expert RH',
    authorAvatar: 'https://i.pravatar.cc/150?img=12',
    thumbnail_url: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=1200',
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    readTime: '8 min',
    views: 1243,
    likes: 89,
    featured: true,
    tags: ['Recrutement', 'RH', 'Guinée', 'Tendances 2025'],
  },
  {
    id: 'blog-2',
    title: 'Intelligence Artificielle et Recrutement : Comment l\'IA Transforme la Sélection des Talents',
    slug: 'ia-recrutement-selection-talents',
    excerpt: 'Découvrez comment l\'intelligence artificielle révolutionne le processus de recrutement et améliore la qualité des embauches.',
    content: `L'intelligence artificielle n'est plus une technologie futuriste mais une réalité qui transforme profondément le recrutement. Matching automatique, scoring des CV, entretiens vidéo analysés par IA...`,
    category: 'Innovation RH',
    author: 'Fatoumata Diallo',
    authorRole: 'Consultante IA & RH',
    authorAvatar: 'https://i.pravatar.cc/150?img=5',
    thumbnail_url: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200',
    publishedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    readTime: '10 min',
    views: 2156,
    likes: 167,
    featured: true,
    tags: ['IA', 'Innovation', 'Recrutement', 'Technologie'],
  },
  {
    id: 'blog-3',
    title: 'Sécurité au Travail dans le Secteur Minier Guinéen : Normes et Bonnes Pratiques',
    slug: 'securite-travail-secteur-minier',
    excerpt: 'Les normes HSE essentielles pour garantir la sécurité des travailleurs dans les mines de Guinée.',
    content: `Le secteur minier guinéen emploie des dizaines de milliers de personnes et représente un pilier de l'économie. La sécurité y est primordiale...`,
    category: 'HSE',
    author: 'Ibrahima Konaté',
    authorRole: 'Ingénieur HSE Senior',
    authorAvatar: 'https://i.pravatar.cc/150?img=33',
    thumbnail_url: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=1200',
    publishedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    readTime: '12 min',
    views: 987,
    likes: 72,
    featured: false,
    tags: ['HSE', 'Sécurité', 'Mines', 'Guinée'],
  },
  {
    id: 'blog-4',
    title: 'Réussir son Entretien d\'Embauche : 10 Conseils d\'Experts',
    slug: 'reussir-entretien-embauche-conseils',
    excerpt: 'Les secrets pour impressionner les recruteurs et décrocher le poste de vos rêves.',
    content: `L'entretien d'embauche est une étape cruciale dans votre recherche d'emploi. Voici 10 conseils d'experts pour maximiser vos chances de succès...`,
    category: 'Carrière',
    author: 'Aminata Soumah',
    authorRole: 'Coach Carrière',
    authorAvatar: 'https://i.pravatar.cc/150?img=9',
    thumbnail_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=1200',
    publishedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    readTime: '6 min',
    views: 3421,
    likes: 234,
    featured: false,
    tags: ['Entretien', 'Conseils', 'Carrière', 'Candidats'],
  },
  {
    id: 'blog-5',
    title: 'Le Droit du Travail en Guinée : Ce Que Tout Employeur Doit Savoir',
    slug: 'droit-travail-guinee-employeurs',
    excerpt: 'Guide pratique sur le Code du Travail guinéen et les obligations légales des entreprises.',
    content: `Le Code du Travail guinéen (Loi L/2014/072/CNT) régit les relations entre employeurs et employés. Connaître vos obligations est essentiel...`,
    category: 'Juridique',
    author: 'Me. Alpha Condé',
    authorRole: 'Avocat Droit Social',
    authorAvatar: 'https://i.pravatar.cc/150?img=68',
    thumbnail_url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1200',
    publishedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    readTime: '15 min',
    views: 1567,
    likes: 98,
    featured: false,
    tags: ['Droit', 'Juridique', 'Employeurs', 'Guinée'],
  },
  {
    id: 'blog-6',
    title: 'Développer ses Compétences Numériques : Les Métiers Tech les Plus Demandés en Guinée',
    slug: 'competences-numeriques-metiers-tech',
    excerpt: 'Les compétences digitales indispensables pour booster votre carrière dans le secteur technologique.',
    content: `La transformation digitale crée de nombreuses opportunités d'emploi en Guinée. Quelles compétences développer pour saisir ces opportunités ?`,
    category: 'Formation',
    author: 'Mohamed Sylla',
    authorRole: 'Formateur Tech',
    authorAvatar: 'https://i.pravatar.cc/150?img=52',
    thumbnail_url: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200',
    publishedAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    readTime: '9 min',
    views: 2098,
    likes: 145,
    featured: true,
    tags: ['Formation', 'Tech', 'Digital', 'Compétences'],
  },
  {
    id: 'blog-7',
    title: 'Construire une Marque Employeur Attractive en Guinée',
    slug: 'marque-employeur-attractive-guinee',
    excerpt: 'Comment attirer et retenir les meilleurs talents en développant une marque employeur forte.',
    content: `Dans un marché de l'emploi compétitif, la marque employeur devient un différenciateur majeur pour attirer les talents...`,
    category: 'RH',
    author: 'Hadja Bah',
    authorRole: 'Consultante RH',
    authorAvatar: 'https://i.pravatar.cc/150?img=20',
    thumbnail_url: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=1200',
    publishedAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
    readTime: '11 min',
    views: 1432,
    likes: 112,
    featured: false,
    tags: ['Marque employeur', 'RH', 'Recrutement', 'Talents'],
  },
  {
    id: 'blog-8',
    title: 'Télétravail et Travail Hybride : Nouvelles Tendances Post-COVID en Guinée',
    slug: 'teletravail-hybride-guinee',
    excerpt: 'Comment les entreprises guinéennes s\'adaptent aux nouvelles formes d\'organisation du travail.',
    content: `Le télétravail, longtemps marginal en Guinée, s'impose progressivement comme une option viable. Quels sont les défis et opportunités ?`,
    category: 'Tendances',
    author: 'Dr. Mamadou Sow',
    authorRole: 'Expert RH',
    authorAvatar: 'https://i.pravatar.cc/150?img=12',
    thumbnail_url: 'https://images.unsplash.com/photo-1588196749597-9ff075ee6b5b?w=1200',
    publishedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    readTime: '7 min',
    views: 1876,
    likes: 134,
    featured: false,
    tags: ['Télétravail', 'Tendances', 'Organisation', 'COVID'],
  },
  {
    id: 'blog-9',
    title: 'Gestion de la Paie en Guinée : Outils et Meilleures Pratiques',
    slug: 'gestion-paie-guinee-outils',
    excerpt: 'Tout ce qu\'il faut savoir sur la gestion de la paie : CNSS, impôts, logiciels et conformité légale.',
    content: `La gestion de la paie est un aspect crucial de la fonction RH. Entre les cotisations CNSS, l'IRPP, les primes et indemnités, maîtriser tous les aspects est essentiel pour la conformité et la satisfaction des employés.`,
    category: 'RH',
    author: 'Aissatou Baldé',
    authorRole: 'Gestionnaire Paie Senior',
    authorAvatar: 'https://i.pravatar.cc/150?img=45',
    thumbnail_url: 'https://images.pexels.com/photos/6801648/pexels-photo-6801648.jpeg?auto=compress&cs=tinysrgb&w=1200',
    publishedAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
    readTime: '13 min',
    views: 2341,
    likes: 189,
    featured: false,
    tags: ['Paie', 'RH', 'CNSS', 'Conformité'],
  },
  {
    id: 'blog-10',
    title: 'Les Soft Skills les Plus Recherchés par les Recruteurs en 2025',
    slug: 'soft-skills-recherches-2025',
    excerpt: 'Au-delà des compétences techniques, découvrez les qualités humaines qui font la différence.',
    content: `Communication, adaptabilité, intelligence émotionnelle, esprit d'équipe... Les soft skills sont devenus aussi importants que les hard skills. Voici celles qui sont les plus valorisées par les employeurs guinéens en 2025.`,
    category: 'Carrière',
    author: 'Ousmane Camara',
    authorRole: 'Consultant Développement Personnel',
    authorAvatar: 'https://i.pravatar.cc/150?img=15',
    thumbnail_url: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=1200',
    publishedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    readTime: '8 min',
    views: 2987,
    likes: 267,
    featured: true,
    tags: ['Soft Skills', 'Carrière', 'Compétences', 'Développement'],
  },
  {
    id: 'blog-11',
    title: 'Égalité Hommes-Femmes en Entreprise : État des Lieux en Guinée',
    slug: 'egalite-hommes-femmes-entreprise-guinee',
    excerpt: 'Où en est la Guinée sur la question de l\'égalité professionnelle ? Chiffres, défis et initiatives.',
    content: `L'égalité professionnelle entre hommes et femmes progresse en Guinée mais reste un défi majeur. Écarts salariaux, accès aux postes de direction, congé maternité : analyse complète de la situation et des solutions.`,
    category: 'Tendances RH',
    author: 'Mariama Sow',
    authorRole: 'Experte Genre & Inclusion',
    authorAvatar: 'https://i.pravatar.cc/150?img=27',
    thumbnail_url: 'https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=1200',
    publishedAt: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
    readTime: '10 min',
    views: 1654,
    likes: 143,
    featured: false,
    tags: ['Égalité', 'Genre', 'Inclusion', 'Tendances'],
  },
  {
    id: 'blog-12',
    title: 'Formation Continue : Investir dans ses Équipes pour Performer',
    slug: 'formation-continue-equipes-performance',
    excerpt: 'Pourquoi et comment mettre en place un plan de formation efficace dans votre entreprise.',
    content: `La formation continue n'est plus un luxe mais une nécessité. Dans un environnement en constante évolution, former ses équipes est la clé de la compétitivité. Budget, identification des besoins, choix des formations, ROI : guide complet pour les DRH.`,
    category: 'Formation',
    author: 'Sékou Touré',
    authorRole: 'Directeur Formation',
    authorAvatar: 'https://i.pravatar.cc/150?img=60',
    thumbnail_url: 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=1200',
    publishedAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
    readTime: '11 min',
    views: 1987,
    likes: 176,
    featured: false,
    tags: ['Formation', 'RH', 'Développement', 'Performance'],
  },
  {
    id: 'blog-13',
    title: 'Prévention des Risques Psychosociaux au Travail',
    slug: 'prevention-risques-psychosociaux-travail',
    excerpt: 'Identifier, prévenir et gérer le stress, le burnout et les conflits en entreprise.',
    content: `Les risques psychosociaux (RPS) sont une réalité en Guinée. Stress chronique, épuisement professionnel, harcèlement : comment les employeurs peuvent créer un environnement de travail sain et prévenir ces risques ?`,
    category: 'Ressources Humaines',
    author: 'Dr. Aïssata Diallo',
    authorRole: 'Psychologue du Travail',
    authorAvatar: 'https://i.pravatar.cc/150?img=38',
    thumbnail_url: 'https://images.pexels.com/photos/3807738/pexels-photo-3807738.jpeg?auto=compress&cs=tinysrgb&w=1200',
    publishedAt: new Date(Date.now() - 42 * 24 * 60 * 60 * 1000).toISOString(),
    readTime: '14 min',
    views: 1432,
    likes: 121,
    featured: false,
    tags: ['Santé', 'Bien-être', 'RPS', 'Management'],
  },
  {
    id: 'blog-14',
    title: 'Entrepreneuriat des Jeunes en Guinée : Opportunités et Défis',
    slug: 'entrepreneuriat-jeunes-guinee-opportunites',
    excerpt: 'Comment la nouvelle génération d\'entrepreneurs transforme le marché du travail guinéen.',
    content: `Les jeunes entrepreneurs guinéens sont de plus en plus nombreux à créer leur propre emploi. Start-ups tech, agribusiness, e-commerce : panorama des secteurs porteurs et des dispositifs d'accompagnement disponibles.`,
    category: 'Tendances',
    author: 'Ibrahim Bah',
    authorRole: 'Consultant Entrepreneuriat',
    authorAvatar: 'https://i.pravatar.cc/150?img=70',
    thumbnail_url: 'https://images.pexels.com/photos/3183197/pexels-photo-3183197.jpeg?auto=compress&cs=tinysrgb&w=1200',
    publishedAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    readTime: '9 min',
    views: 3124,
    likes: 298,
    featured: true,
    tags: ['Entrepreneuriat', 'Jeunes', 'Start-up', 'Innovation'],
  },
  {
    id: 'blog-15',
    title: 'Optimiser son CV pour les ATS : Guide Pratique',
    slug: 'optimiser-cv-ats-guide-pratique',
    excerpt: 'Comment adapter votre CV pour qu\'il soit lu et approuvé par les systèmes de recrutement automatisés.',
    content: `Les ATS (Applicant Tracking Systems) filtrent aujourd'hui la majorité des candidatures. Mots-clés, format, structure : découvrez comment optimiser votre CV pour passer ces systèmes et atteindre les recruteurs.`,
    category: 'Carrière',
    author: 'Kadiatou Diallo',
    authorRole: 'Consultante Carrière',
    authorAvatar: 'https://i.pravatar.cc/150?img=32',
    thumbnail_url: 'https://images.pexels.com/photos/4065876/pexels-photo-4065876.jpeg?auto=compress&cs=tinysrgb&w=1200',
    publishedAt: new Date(Date.now() - 48 * 24 * 60 * 60 * 1000).toISOString(),
    readTime: '7 min',
    views: 2765,
    likes: 234,
    featured: false,
    tags: ['CV', 'ATS', 'Candidature', 'Conseils'],
  },
];

export const blogCategories = [
  { id: 'all', name: 'Tous les articles', count: sampleBlogPosts.length },
  { id: 'Recrutement', name: 'Recrutement', count: sampleBlogPosts.filter(p => p.category === 'Recrutement').length },
  { id: 'Innovation RH', name: 'Innovation RH', count: sampleBlogPosts.filter(p => p.category === 'Innovation RH').length },
  { id: 'HSE', name: 'HSE', count: sampleBlogPosts.filter(p => p.category === 'HSE').length },
  { id: 'Carrière', name: 'Carrière', count: sampleBlogPosts.filter(p => p.category === 'Carrière').length },
  { id: 'Juridique', name: 'Juridique', count: sampleBlogPosts.filter(p => p.category === 'Juridique').length },
  { id: 'Formation', name: 'Formation', count: sampleBlogPosts.filter(p => p.category === 'Formation').length },
  { id: 'RH', name: 'RH', count: sampleBlogPosts.filter(p => p.category === 'RH').length },
  { id: 'Tendances', name: 'Tendances', count: sampleBlogPosts.filter(p => p.category === 'Tendances').length },
  { id: 'Tendances RH', name: 'Tendances RH', count: sampleBlogPosts.filter(p => p.category === 'Tendances RH').length },
  { id: 'Ressources Humaines', name: 'Ressources Humaines', count: sampleBlogPosts.filter(p => p.category === 'Ressources Humaines').length },
];
