export const sampleResources = [
  {
    id: 'res-1',
    title: 'Guide Complet du CV Professionnel 2024',
    description: 'Apprenez à créer un CV percutant qui attire l\'attention des recruteurs guinéens. Inclut des modèles et des exemples concrets.',
    category: 'guide',
    file_url: '#',
    file_type: 'pdf',
    file_size: '2.5 MB',
    thumbnail_url: 'https://images.pexels.com/photos/590016/pexels-photo-590016.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Mamadou Diallo',
    download_count: 1245,
    tags: ['CV', 'Recrutement', 'Carrière'],
    published: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'res-2',
    title: 'Code du Travail Guinéen - Version Annotée',
    description: 'Document complet du Code du Travail de Guinée avec annotations et explications pratiques pour employeurs et employés.',
    category: 'document',
    file_url: '#',
    file_type: 'pdf',
    file_size: '5.8 MB',
    thumbnail_url: 'https://images.pexels.com/photos/8111849/pexels-photo-8111849.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Ministère du Travail',
    download_count: 3421,
    tags: ['Droit', 'Juridique', 'Législation'],
    published: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'res-3',
    title: 'Modèles de Lettres de Motivation',
    description: '50 modèles de lettres de motivation adaptés au contexte guinéen pour différents secteurs et niveaux d\'expérience.',
    category: 'template',
    file_url: '#',
    file_type: 'docx',
    file_size: '1.2 MB',
    thumbnail_url: 'https://images.pexels.com/photos/4226140/pexels-photo-4226140.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Fatoumata Camara',
    download_count: 2103,
    tags: ['Lettre', 'Motivation', 'Emploi'],
    published: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'res-4',
    title: 'Guide des Salaires en Guinée 2024',
    description: 'Étude complète des salaires par secteur et par fonction en Guinée. Données actualisées pour négocier votre rémunération.',
    category: 'ebook',
    file_url: '#',
    file_type: 'pdf',
    file_size: '3.1 MB',
    thumbnail_url: 'https://images.pexels.com/photos/6863332/pexels-photo-6863332.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Alpha Condé',
    download_count: 1876,
    tags: ['Salaire', 'Rémunération', 'Statistiques'],
    published: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'res-5',
    title: 'Kit Entrepreneur Guinéen',
    description: 'Tous les documents nécessaires pour créer votre entreprise en Guinée : statuts, registre, déclarations fiscales, etc.',
    category: 'document',
    file_url: '#',
    file_type: 'zip',
    file_size: '4.7 MB',
    thumbnail_url: 'https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'APIP Guinée',
    download_count: 892,
    tags: ['Entrepreneuriat', 'Business', 'Juridique'],
    published: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'res-6',
    title: 'Logiciel de Gestion des Candidatures',
    description: 'Outil gratuit et simple pour gérer vos candidatures, suivre vos postulations et organiser votre recherche d\'emploi.',
    category: 'software',
    file_url: '#',
    file_type: 'exe',
    file_size: '15.4 MB',
    thumbnail_url: 'https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'JobGuinée Tech',
    download_count: 567,
    tags: ['Logiciel', 'Candidature', 'Organisation'],
    published: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'res-7',
    title: 'E-book: Réussir son Entretien d\'Embauche',
    description: 'Livre numérique de 120 pages avec toutes les techniques pour briller lors de vos entretiens. Cas pratiques guinéens inclus.',
    category: 'ebook',
    file_url: '#',
    file_type: 'epub',
    file_size: '2.8 MB',
    thumbnail_url: 'https://images.pexels.com/photos/5668858/pexels-photo-5668858.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Ibrahima Sory',
    download_count: 2234,
    tags: ['Entretien', 'Recrutement', 'Conseils'],
    published: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'res-8',
    title: 'Calendrier Fiscal Guinéen 2024',
    description: 'Tous les échéances fiscales et déclarations obligatoires pour les entreprises et professionnels en Guinée.',
    category: 'document',
    file_url: '#',
    file_type: 'pdf',
    file_size: '890 KB',
    thumbnail_url: 'https://images.pexels.com/photos/6694543/pexels-photo-6694543.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Direction Générale des Impôts',
    download_count: 1654,
    tags: ['Fiscal', 'Impôts', 'Calendrier'],
    published: true,
    created_at: new Date().toISOString()
  },
  {
    id: 'res-9',
    title: 'Modèles de Contrats de Travail',
    description: 'Collection de modèles de contrats conformes au droit guinéen : CDI, CDD, stage, apprentissage, consultant.',
    category: 'template',
    file_url: '#',
    file_type: 'docx',
    file_size: '1.5 MB',
    thumbnail_url: 'https://images.pexels.com/photos/4427430/pexels-photo-4427430.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Cabinet Juridique Diallo & Associés',
    download_count: 3102,
    tags: ['Contrat', 'Juridique', 'RH'],
    published: true,
    created_at: new Date().toISOString()
  }
];
