export const sampleProfiles = [
  {
    title: 'Assistant RH Junior',
    bio: 'Diplômé en gestion des ressources humaines avec une passion pour le recrutement et la formation. Maîtrise des outils bureautiques et bonne capacité relationnelle.',
    skills: ['Recrutement', 'MS Office', 'Communication', 'Gestion administrative'],
    experience_years: 1,
    education_level: 'Licence',
    location: 'Conakry',
    languages: ['Français', 'Anglais'],
    preferred_contract_type: 'CDI',
    mobility: 'Nationale',
    is_verified: true,
    visibility: 'public',
    profile_price: 4000,
    nationality: 'Guinéenne'
  },
  {
    title: 'Développeur Web Débutant',
    bio: 'Jeune développeur passionné par les technologies web modernes. Formation en développement fullstack avec projets personnels GitHub actifs.',
    skills: ['JavaScript', 'React', 'HTML/CSS', 'Node.js', 'Git'],
    experience_years: 1,
    education_level: 'BTS/DUT',
    location: 'Conakry',
    languages: ['Français', 'Anglais'],
    preferred_contract_type: 'CDD',
    mobility: 'Nationale',
    is_verified: true,
    visibility: 'public',
    profile_price: 4000,
    nationality: 'Guinéenne'
  },
  {
    title: 'Comptable Assistant',
    bio: 'Formation en comptabilité OHADA avec stage en cabinet comptable. Rigueur et sens de l\'organisation.',
    skills: ['Comptabilité OHADA', 'Excel', 'Sage', 'Fiscalité'],
    experience_years: 2,
    education_level: 'Licence',
    location: 'Kindia',
    languages: ['Français'],
    preferred_contract_type: 'CDI',
    mobility: 'Nationale',
    is_verified: false,
    visibility: 'public',
    profile_price: 4000,
    nationality: 'Guinéenne'
  },
  {
    title: 'Agent de Sécurité',
    bio: 'Formation en sécurité privée avec certificat. Ponctuel, vigilant et respectueux des consignes.',
    skills: ['Surveillance', 'Prévention', 'Secourisme', 'Gestion de conflits'],
    experience_years: 2,
    education_level: 'Baccalauréat',
    location: 'Boké',
    languages: ['Français', 'Soussou'],
    preferred_contract_type: 'CDD',
    mobility: 'Régionale',
    is_verified: true,
    visibility: 'public',
    profile_price: 4000,
    nationality: 'Guinéenne'
  },
  {
    title: 'Secrétaire de Direction',
    bio: 'Diplômée en secrétariat de direction. Excellente maîtrise de l\'orthographe et des outils bureautiques.',
    skills: ['Secrétariat', 'MS Office', 'Rédaction', 'Accueil', 'Gestion agenda'],
    experience_years: 1,
    education_level: 'BTS/DUT',
    location: 'Conakry',
    languages: ['Français', 'Anglais'],
    preferred_contract_type: 'CDI',
    mobility: 'Nationale',
    is_verified: true,
    visibility: 'public',
    profile_price: 4000,
    nationality: 'Guinéenne'
  },
  {
    title: 'Opérateur de Saisie',
    bio: 'Rapidité de frappe et précision dans la saisie de données. Formation bureautique complète.',
    skills: ['Saisie rapide', 'Excel', 'Word', 'Gestion base de données'],
    experience_years: 1,
    education_level: 'Baccalauréat',
    location: 'Kankan',
    languages: ['Français'],
    preferred_contract_type: 'CDD',
    mobility: 'Nationale',
    is_verified: false,
    visibility: 'public',
    profile_price: 4000,
    nationality: 'Guinéenne'
  },
  {
    title: 'Chargé Marketing Junior',
    bio: 'Formation en marketing digital avec certification Google Analytics. Créatif et orienté résultats.',
    skills: ['Marketing digital', 'Réseaux sociaux', 'Google Ads', 'Content marketing', 'Canva'],
    experience_years: 2,
    education_level: 'Licence',
    location: 'Conakry',
    languages: ['Français', 'Anglais'],
    preferred_contract_type: 'CDI',
    mobility: 'Nationale',
    is_verified: true,
    visibility: 'public',
    profile_price: 4000,
    nationality: 'Guinéenne'
  },
  {
    title: 'Technicien Informatique',
    bio: 'Maintenance informatique et support utilisateur. Installation systèmes et résolution problèmes.',
    skills: ['Maintenance PC', 'Windows', 'Réseau', 'Support technique'],
    experience_years: 2,
    education_level: 'BTS/DUT',
    location: 'Labé',
    languages: ['Français'],
    preferred_contract_type: 'CDD',
    mobility: 'Nationale',
    is_verified: false,
    visibility: 'public',
    profile_price: 4000,
    nationality: 'Guinéenne'
  },
  {
    title: 'Responsable RH',
    bio: 'Expérience confirmée en gestion RH complète : recrutement, formation, paie et gestion des conflits. Connaissance du droit du travail guinéen.',
    skills: ['Gestion RH', 'Recrutement', 'Paie', 'Formation', 'Droit du travail', 'Relations sociales'],
    experience_years: 4,
    education_level: 'Master',
    location: 'Conakry',
    languages: ['Français', 'Anglais'],
    preferred_contract_type: 'CDI',
    mobility: 'Nationale',
    is_verified: true,
    visibility: 'public',
    profile_price: 8000,
    nationality: 'Guinéenne'
  },
  {
    title: 'Chef Comptable',
    bio: 'Expert en comptabilité OHADA avec expérience en audit et clôture de comptes. Maîtrise des logiciels comptables.',
    skills: ['Comptabilité OHADA', 'Audit', 'Fiscalité', 'Sage', 'Reporting financier', 'Analyse financière'],
    experience_years: 5,
    education_level: 'Master',
    location: 'Conakry',
    languages: ['Français', 'Anglais'],
    preferred_contract_type: 'CDI',
    mobility: 'Internationale',
    is_verified: true,
    visibility: 'public',
    profile_price: 8000,
    nationality: 'Guinéenne'
  },
  {
    title: 'Ingénieur Électricité Industrielle',
    bio: 'Maintenance et installation électrique en milieu industriel. Expérience secteur minier.',
    skills: ['Électricité industrielle', 'Maintenance préventive', 'AutoCAD', 'Lecture plans', 'Normes sécurité', 'Supervision'],
    experience_years: 4,
    education_level: 'Master',
    location: 'Boké',
    languages: ['Français', 'Anglais'],
    preferred_contract_type: 'CDI',
    mobility: 'Internationale',
    is_verified: true,
    visibility: 'public',
    profile_price: 8000,
    nationality: 'Guinéenne'
  },
  {
    title: 'Chef de Projet IT',
    bio: 'Gestion de projets informatiques de A à Z. Méthodologies agiles et traditionnelles.',
    skills: ['Gestion de projet', 'Agile/Scrum', 'IT Management', 'Budget', 'Leadership'],
    experience_years: 4,
    education_level: 'Master',
    location: 'Conakry',
    languages: ['Français', 'Anglais'],
    preferred_contract_type: 'CDI',
    mobility: 'Nationale',
    is_verified: true,
    visibility: 'public',
    profile_price: 8000,
    nationality: 'Guinéenne'
  },
  {
    title: 'Superviseur Logistique',
    bio: 'Gestion d\'entrepôt et coordination transport. Optimisation des flux et gestion stocks.',
    skills: ['Logistique', 'Gestion stocks', 'Transport', 'SAP', 'Coordination', 'Supply chain'],
    experience_years: 5,
    education_level: 'Licence',
    location: 'Kamsar',
    languages: ['Français', 'Anglais'],
    preferred_contract_type: 'CDI',
    mobility: 'Nationale',
    is_verified: true,
    visibility: 'public',
    profile_price: 8000,
    nationality: 'Guinéenne'
  },
  {
    title: 'Responsable Qualité HSE',
    bio: 'Expert en normes ISO et sécurité au travail. Audits et mise en conformité.',
    skills: ['ISO 9001', 'HSE', 'Audit qualité', 'Normes sécurité', 'Formation sécurité', 'Évaluation risques'],
    experience_years: 4,
    education_level: 'Master',
    location: 'Conakry',
    languages: ['Français', 'Anglais'],
    preferred_contract_type: 'CDI',
    mobility: 'Internationale',
    is_verified: true,
    visibility: 'public',
    profile_price: 8000,
    nationality: 'Guinéenne'
  },
  {
    title: 'Chauffeur Poids Lourds',
    bio: 'Expérience transport de marchandises et engins. Permis C et E. Ponctuel et responsable.',
    skills: ['Conduite poids lourd', 'Mécanique de base', 'Respect délais', 'Gestion itinéraire'],
    experience_years: 5,
    education_level: 'Baccalauréat',
    location: 'Boké',
    languages: ['Français'],
    preferred_contract_type: 'CDI',
    mobility: 'Nationale',
    is_verified: true,
    visibility: 'public',
    profile_price: 8000,
    nationality: 'Guinéenne'
  },
  {
    title: 'Géologue Minier',
    bio: 'Exploration et analyse géologique. Expérience en cartographie et échantillonnage.',
    skills: ['Géologie', 'Cartographie', 'Échantillonnage', 'Analyse terrain', 'Logiciels géologie', 'Rédaction rapports'],
    experience_years: 4,
    education_level: 'Master',
    location: 'Siguiri',
    languages: ['Français', 'Anglais'],
    preferred_contract_type: 'CDI',
    mobility: 'Internationale',
    is_verified: true,
    visibility: 'public',
    profile_price: 8000,
    nationality: 'Guinéenne'
  },
  {
    title: 'Directeur des Ressources Humaines',
    bio: 'Plus de 10 ans d\'expérience en gestion RH stratégique. Pilotage SIRH, politiques RH et relations sociales.',
    skills: ['Management RH', 'Stratégie RH', 'SIRH', 'Négociation sociale', 'Développement RH', 'Budget RH', 'Leadership'],
    experience_years: 10,
    education_level: 'Master',
    location: 'Conakry',
    languages: ['Français', 'Anglais'],
    preferred_contract_type: 'CDI',
    mobility: 'Internationale',
    is_verified: true,
    visibility: 'public',
    profile_price: 15000,
    nationality: 'Guinéenne'
  },
  {
    title: 'Directeur Financier',
    bio: 'Expert en gestion financière d\'entreprise. Stratégie financière, consolidation et contrôle de gestion.',
    skills: ['Finance d\'entreprise', 'Consolidation', 'Contrôle de gestion', 'IFRS', 'OHADA', 'Trésorerie', 'Budget', 'Audit'],
    experience_years: 12,
    education_level: 'Master',
    location: 'Conakry',
    languages: ['Français', 'Anglais'],
    preferred_contract_type: 'CDI',
    mobility: 'Internationale',
    is_verified: true,
    visibility: 'public',
    profile_price: 15000,
    nationality: 'Guinéenne'
  },
  {
    title: 'Ingénieur Maintenance Mines Senior',
    bio: 'Expert en maintenance d\'équipements miniers lourds. Gestion d\'équipe et planification maintenance.',
    skills: ['Maintenance minière', 'Engins lourds', 'Planification', 'Management', 'Diagnostic pannes', 'Optimisation coûts', 'Sécurité'],
    experience_years: 8,
    education_level: 'Master',
    location: 'Boké',
    languages: ['Français', 'Anglais'],
    preferred_contract_type: 'CDI',
    mobility: 'Internationale',
    is_verified: true,
    visibility: 'public',
    profile_price: 15000,
    nationality: 'Guinéenne'
  },
  {
    title: 'Directeur de Projet BTP',
    bio: 'Conduite de grands projets de construction. Coordination multi-métiers et gestion budgets importants.',
    skills: ['Gestion projet BTP', 'Coordination chantier', 'Budget', 'Planning', 'Normes construction', 'Management équipes', 'Négociation'],
    experience_years: 9,
    education_level: 'Master',
    location: 'Conakry',
    languages: ['Français', 'Anglais'],
    preferred_contract_type: 'CDI',
    mobility: 'Internationale',
    is_verified: true,
    visibility: 'public',
    profile_price: 15000,
    nationality: 'Guinéenne'
  },
  {
    title: 'Responsable Supply Chain',
    bio: 'Expert en optimisation de chaîne logistique. Réduction coûts et amélioration performance.',
    skills: ['Supply chain', 'Optimisation flux', 'Achats', 'Gestion stocks', 'Négociation fournisseurs', 'ERP', 'Analytics'],
    experience_years: 7,
    education_level: 'Master',
    location: 'Conakry',
    languages: ['Français', 'Anglais'],
    preferred_contract_type: 'CDI',
    mobility: 'Internationale',
    is_verified: true,
    visibility: 'public',
    profile_price: 15000,
    nationality: 'Guinéenne'
  },
  {
    title: 'Chef de Sécurité Groupe',
    bio: 'Expert sécurité industrielle et protection personnes. Formation équipes et gestion crises.',
    skills: ['Sécurité industrielle', 'Gestion crises', 'Formation sécurité', 'Évaluation risques', 'Plans urgence', 'Management', 'Audit sécurité'],
    experience_years: 10,
    education_level: 'Master',
    location: 'Boké',
    languages: ['Français', 'Anglais'],
    preferred_contract_type: 'CDI',
    mobility: 'Internationale',
    is_verified: true,
    visibility: 'public',
    profile_price: 15000,
    nationality: 'Guinéenne'
  },
  {
    title: 'Directeur des Opérations',
    bio: 'Management opérationnel global. Optimisation processus et performance organisationnelle.',
    skills: ['Management opérationnel', 'Amélioration continue', 'KPI', 'Lean management', 'Stratégie', 'Budget', 'Leadership'],
    experience_years: 11,
    education_level: 'Master',
    location: 'Conakry',
    languages: ['Français', 'Anglais'],
    preferred_contract_type: 'CDI',
    mobility: 'Internationale',
    is_verified: true,
    visibility: 'public',
    profile_price: 15000,
    nationality: 'Guinéenne'
  },
  {
    title: 'Architecte Système d\'Information',
    bio: 'Conception architecture SI complexes. Cloud, sécurité et transformation digitale.',
    skills: ['Architecture SI', 'Cloud (AWS/Azure)', 'Sécurité IT', 'DevOps', 'Microservices', 'Transformation digitale', 'Management'],
    experience_years: 8,
    education_level: 'Master',
    location: 'Conakry',
    languages: ['Français', 'Anglais'],
    preferred_contract_type: 'CDI',
    mobility: 'Internationale',
    is_verified: true,
    visibility: 'public',
    profile_price: 15000,
    nationality: 'Guinéenne'
  }
];
