export const sampleBlogPosts = [
  {
    id: 'blog-1',
    title: 'Guide Complet du Recrutement en Guinée en 2025',
    slug: 'guide-recrutement-guinee-2025',
    excerpt: 'Tout ce que vous devez savoir sur le recrutement en Guinée : tendances, meilleures pratiques, aspects légaux et conseils d\'experts.',
    content: `Le marché de l'emploi guinéen connaît une transformation profonde en 2025. Entre digitalisation, nouvelles attentes des candidats et évolutions réglementaires, recruter efficacement demande une approche modernisée...`,
    category: 'Recrutement',
    author: 'Dr. Mamadou Sow',
    authorRole: 'Expert RH',
    authorAvatar: 'https://i.pravatar.cc/150?img=12',
    image: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=1200',
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    readTime: '8 min',
    views: 1243,
    likes: 89,
    featured: true,
    tags: ['Recrutement', 'RH', 'Guinée', 'Tendances 2025'],
  },
  {
    id: 'blog-2',
    title: 'Intelligence Artificielle et Recrutement : Comment l\'IA Transforme la Sélection des Talents',
    slug: 'ia-recrutement-selection-talents',
    excerpt: 'Découvrez comment l\'intelligence artificielle révolutionne le processus de recrutement et améliore la qualité des embauches.',
    content: `L'intelligence artificielle n'est plus une technologie futuriste mais une réalité qui transforme profondément le recrutement. Matching automatique, scoring des CV, entretiens vidéo analysés par IA...`,
    category: 'Innovation RH',
    author: 'Fatoumata Diallo',
    authorRole: 'Consultante IA & RH',
    authorAvatar: 'https://i.pravatar.cc/150?img=5',
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200',
    publishedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    readTime: '10 min',
    views: 2156,
    likes: 167,
    featured: true,
    tags: ['IA', 'Innovation', 'Recrutement', 'Technologie'],
  },
  {
    id: 'blog-3',
    title: 'Sécurité au Travail dans le Secteur Minier Guinéen : Normes et Bonnes Pratiques',
    slug: 'securite-travail-secteur-minier',
    excerpt: 'Les normes HSE essentielles pour garantir la sécurité des travailleurs dans les mines de Guinée.',
    content: `Le secteur minier guinéen emploie des dizaines de milliers de personnes et représente un pilier de l'économie. La sécurité y est primordiale...`,
    category: 'HSE',
    author: 'Ibrahima Konaté',
    authorRole: 'Ingénieur HSE Senior',
    authorAvatar: 'https://i.pravatar.cc/150?img=33',
    image: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=1200',
    publishedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    readTime: '12 min',
    views: 987,
    likes: 72,
    featured: false,
    tags: ['HSE', 'Sécurité', 'Mines', 'Guinée'],
  },
  {
    id: 'blog-4',
    title: 'Réussir son Entretien d\'Embauche : 10 Conseils d\'Experts',
    slug: 'reussir-entretien-embauche-conseils',
    excerpt: 'Les secrets pour impressionner les recruteurs et décrocher le poste de vos rêves.',
    content: `L'entretien d'embauche est une étape cruciale dans votre recherche d'emploi. Voici 10 conseils d'experts pour maximiser vos chances de succès...`,
    category: 'Carrière',
    author: 'Aminata Soumah',
    authorRole: 'Coach Carrière',
    authorAvatar: 'https://i.pravatar.cc/150?img=9',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=1200',
    publishedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    readTime: '6 min',
    views: 3421,
    likes: 234,
    featured: false,
    tags: ['Entretien', 'Conseils', 'Carrière', 'Candidats'],
  },
  {
    id: 'blog-5',
    title: 'Le Droit du Travail en Guinée : Ce Que Tout Employeur Doit Savoir',
    slug: 'droit-travail-guinee-employeurs',
    excerpt: 'Guide pratique sur le Code du Travail guinéen et les obligations légales des entreprises.',
    content: `Le Code du Travail guinéen (Loi L/2014/072/CNT) régit les relations entre employeurs et employés. Connaître vos obligations est essentiel...`,
    category: 'Juridique',
    author: 'Me. Alpha Condé',
    authorRole: 'Avocat Droit Social',
    authorAvatar: 'https://i.pravatar.cc/150?img=68',
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1200',
    publishedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    readTime: '15 min',
    views: 1567,
    likes: 98,
    featured: false,
    tags: ['Droit', 'Juridique', 'Employeurs', 'Guinée'],
  },
  {
    id: 'blog-6',
    title: 'Développer ses Compétences Numériques : Les Métiers Tech les Plus Demandés en Guinée',
    slug: 'competences-numeriques-metiers-tech',
    excerpt: 'Les compétences digitales indispensables pour booster votre carrière dans le secteur technologique.',
    content: `La transformation digitale crée de nombreuses opportunités d'emploi en Guinée. Quelles compétences développer pour saisir ces opportunités ?`,
    category: 'Formation',
    author: 'Mohamed Sylla',
    authorRole: 'Formateur Tech',
    authorAvatar: 'https://i.pravatar.cc/150?img=52',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200',
    publishedAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    readTime: '9 min',
    views: 2098,
    likes: 145,
    featured: true,
    tags: ['Formation', 'Tech', 'Digital', 'Compétences'],
  },
  {
    id: 'blog-7',
    title: 'Construire une Marque Employeur Attractive en Guinée',
    slug: 'marque-employeur-attractive-guinee',
    excerpt: 'Comment attirer et retenir les meilleurs talents en développant une marque employeur forte.',
    content: `Dans un marché de l'emploi compétitif, la marque employeur devient un différenciateur majeur pour attirer les talents...`,
    category: 'RH',
    author: 'Hadja Bah',
    authorRole: 'Consultante RH',
    authorAvatar: 'https://i.pravatar.cc/150?img=20',
    image: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=1200',
    publishedAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
    readTime: '11 min',
    views: 1432,
    likes: 112,
    featured: false,
    tags: ['Marque employeur', 'RH', 'Recrutement', 'Talents'],
  },
  {
    id: 'blog-8',
    title: 'Télétravail et Travail Hybride : Nouvelles Tendances Post-COVID en Guinée',
    slug: 'teletravail-hybride-guinee',
    excerpt: 'Comment les entreprises guinéennes s\'adaptent aux nouvelles formes d\'organisation du travail.',
    content: `Le télétravail, longtemps marginal en Guinée, s'impose progressivement comme une option viable. Quels sont les défis et opportunités ?`,
    category: 'Tendances',
    author: 'Dr. Mamadou Sow',
    authorRole: 'Expert RH',
    authorAvatar: 'https://i.pravatar.cc/150?img=12',
    image: 'https://images.unsplash.com/photo-1588196749597-9ff075ee6b5b?w=1200',
    publishedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    readTime: '7 min',
    views: 1876,
    likes: 134,
    featured: false,
    tags: ['Télétravail', 'Tendances', 'Organisation', 'COVID'],
  },
];

export const blogCategories = [
  { id: 'all', name: 'Tous les articles', count: sampleBlogPosts.length },
  { id: 'Recrutement', name: 'Recrutement', count: sampleBlogPosts.filter(p => p.category === 'Recrutement').length },
  { id: 'Innovation RH', name: 'Innovation RH', count: sampleBlogPosts.filter(p => p.category === 'Innovation RH').length },
  { id: 'HSE', name: 'HSE', count: sampleBlogPosts.filter(p => p.category === 'HSE').length },
  { id: 'Carrière', name: 'Carrière', count: sampleBlogPosts.filter(p => p.category === 'Carrière').length },
  { id: 'Juridique', name: 'Juridique', count: sampleBlogPosts.filter(p => p.category === 'Juridique').length },
  { id: 'Formation', name: 'Formation', count: sampleBlogPosts.filter(p => p.category === 'Formation').length },
  { id: 'RH', name: 'RH', count: sampleBlogPosts.filter(p => p.category === 'RH').length },
  { id: 'Tendances', name: 'Tendances', count: sampleBlogPosts.filter(p => p.category === 'Tendances').length },
];
