export const testimonials = [
  {
    id: 1,
    name: 'Mamadou Diallo',
    role: 'Ingénieur Civil',
    company: 'Mining Corp Guinée',
    avatar: 'https://i.pravatar.cc/150?img=12',
    content: 'Grâce à JobGuinée, j\'ai trouvé mon poste de rêve en moins de 2 semaines ! La plateforme est intuitive et les offres sont de qualité. Je recommande vivement.',
    rating: 5,
    date: '2024-10-15',
  },
  {
    id: 2,
    name: 'Fatoumata Camara',
    role: 'Responsable RH',
    company: 'Groupe Industriel Guinéen',
    avatar: 'https://i.pravatar.cc/150?img=5',
    content: 'En tant que recruteur, JobGuinée m\'a permis de recevoir des candidatures qualifiées rapidement. L\'outil de tri IA est vraiment performant.',
    rating: 5,
    date: '2024-09-28',
  },
  {
    id: 3,
    name: 'Ibrahima Bah',
    role: 'Manager HSE',
    company: 'Bauxite International',
    avatar: 'https://i.pravatar.cc/150?img=33',
    content: 'Interface moderne, recherche facile et notifications en temps réel. JobGuinée transforme vraiment la recherche d\'emploi en Guinée.',
    rating: 5,
    date: '2024-10-01',
  },
  {
    id: 4,
    name: 'Aminata Soumah',
    role: 'Digital Marketing Manager',
    company: 'Digital Guinée Agency',
    avatar: 'https://i.pravatar.cc/150?img=9',
    content: 'J\'ai pu publier mes offres et gérer mes candidatures depuis le tableau de bord recruteur. Tout est centralisé et efficace.',
    rating: 5,
    date: '2024-09-20',
  },
  {
    id: 5,
    name: 'Mohamed Sylla',
    role: 'Développeur Full Stack',
    company: 'TechHub Africa',
    avatar: 'https://i.pravatar.cc/150?img=52',
    content: 'La CVthèque premium m\'a permis de me faire repérer par plusieurs recruteurs. Mon profil a eu 45 vues en une semaine !',
    rating: 5,
    date: '2024-10-10',
  },
  {
    id: 6,
    name: 'Hadja Kaba',
    role: 'Chef de Projet',
    company: 'Finance Solutions',
    avatar: 'https://i.pravatar.cc/150?img=20',
    content: 'Les alertes emploi personnalisées me permettent de ne manquer aucune opportunité dans mon domaine. Service excellent !',
    rating: 5,
    date: '2024-09-15',
  },
];

export const companies = [
  {
    id: 'comp-1',
    name: 'Mining Corp Guinée',
    logo: 'https://ui-avatars.com/api/?name=Mining+Corp&background=0E2F56&color=fff&size=200',
    activeJobs: 8,
    sector: 'Mines et Carrières',
  },
  {
    id: 'comp-2',
    name: 'Bauxite International',
    logo: 'https://ui-avatars.com/api/?name=Bauxite+Int&background=059669&color=fff&size=200',
    activeJobs: 12,
    sector: 'Mines et Carrières',
  },
  {
    id: 'comp-3',
    name: 'Digital Guinée Agency',
    logo: 'https://ui-avatars.com/api/?name=Digital+Agency&background=FF8C00&color=fff&size=200',
    activeJobs: 5,
    sector: 'Marketing & Digital',
  },
  {
    id: 'comp-4',
    name: 'TechHub Africa',
    logo: 'https://ui-avatars.com/api/?name=TechHub&background=8B5CF6&color=fff&size=200',
    activeJobs: 7,
    sector: 'Technologies',
  },
  {
    id: 'comp-5',
    name: 'Groupe Industriel Guinéen',
    logo: 'https://ui-avatars.com/api/?name=GIG&background=DC2626&color=fff&size=200',
    activeJobs: 15,
    sector: 'Industrie',
  },
  {
    id: 'comp-6',
    name: 'Finance Solutions Guinée',
    logo: 'https://ui-avatars.com/api/?name=Finance+Solutions&background=10B981&color=fff&size=200',
    activeJobs: 6,
    sector: 'Finance et Banque',
  },
  {
    id: 'comp-7',
    name: 'BTP Guinée Construction',
    logo: 'https://ui-avatars.com/api/?name=BTP+Guinee&background=F59E0B&color=fff&size=200',
    activeJobs: 10,
    sector: 'BTP et Construction',
  },
  {
    id: 'comp-8',
    name: 'Santé Plus Clinique',
    logo: 'https://ui-avatars.com/api/?name=Sante+Plus&background=EF4444&color=fff&size=200',
    activeJobs: 4,
    sector: 'Santé',
  },
];

export const jobCategories = [
  {
    id: 'cat-1',
    name: 'Mines et Carrières',
    icon: '⛏️',
    count: 45,
    color: 'from-gray-600 to-gray-800',
  },
  {
    id: 'cat-2',
    name: 'BTP et Construction',
    icon: '🏗️',
    count: 38,
    color: 'from-orange-500 to-orange-700',
  },
  {
    id: 'cat-3',
    name: 'Finance et Banque',
    icon: '💰',
    count: 29,
    color: 'from-green-500 to-green-700',
  },
  {
    id: 'cat-4',
    name: 'Ressources Humaines',
    icon: '👥',
    count: 22,
    color: 'from-blue-500 to-blue-700',
  },
  {
    id: 'cat-5',
    name: 'Technologies',
    icon: '💻',
    count: 34,
    color: 'from-purple-500 to-purple-700',
  },
  {
    id: 'cat-6',
    name: 'Santé',
    icon: '🏥',
    count: 18,
    color: 'from-red-500 to-red-700',
  },
  {
    id: 'cat-7',
    name: 'Logistique et Transport',
    icon: '🚛',
    count: 25,
    color: 'from-indigo-500 to-indigo-700',
  },
  {
    id: 'cat-8',
    name: 'Énergie',
    icon: '⚡',
    count: 16,
    color: 'from-yellow-500 to-yellow-700',
  },
];

export const guineaRegions = [
  { name: 'Conakry', jobs: 156, lat: 9.6412, lng: -13.5784 },
  { name: 'Boké', jobs: 45, lat: 10.9425, lng: -14.2917 },
  { name: 'Kamsar', jobs: 38, lat: 10.6667, lng: -14.6167 },
  { name: 'Kindia', jobs: 28, lat: 10.0667, lng: -12.85 },
  { name: 'Labé', jobs: 22, lat: 11.3167, lng: -12.2833 },
  { name: 'Nzérékoré', jobs: 19, lat: 7.75, lng: -8.8167 },
  { name: 'Kankan', jobs: 25, lat: 10.3833, lng: -9.3056 },
  { name: 'Siguiri', jobs: 31, lat: 11.4167, lng: -9.1667 },
  { name: 'Mamou', jobs: 15, lat: 10.3667, lng: -12.0833 },
  { name: 'Faranah', jobs: 12, lat: 10.0333, lng: -10.7333 },
];
