export const testimonials = [
  {
    id: 1,
    name: 'Mamadou Baldé',
    role: 'Technicien Mines',
    company: 'Société Minière de Boké',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=MamadouBalde&skinColor=brown&top=shortFlat&accessories=blank&clothingColor=1e3a5f',
    content: 'Après 6 mois de recherche, j\'ai décroché un poste à Boké grâce à JobGuinée. Les alertes m\'ont notifié dès la publication de l\'offre. Plateforme vraiment adaptée au marché guinéen !',
    rating: 5,
    date: '2025-11-15',
  },
  {
    id: 2,
    name: 'Fatoumata Sylla',
    role: 'Comptable',
    company: 'Groupe Commercial Conakry',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=FatoumataSylla&skinColor=darkBrown&top=hijab&accessories=blank&clothingColor=ff8c00',
    content: 'En tant que femme dans la finance à Conakry, trouver un emploi stable n\'était pas facile. JobGuinée m\'a connectée directement avec des recruteurs sérieux. Je recommande à toutes les sœurs !',
    rating: 5,
    date: '2025-10-28',
  },
  {
    id: 3,
    name: 'Ibrahima Camara',
    role: 'Conducteur d\'engins',
    company: 'BTP Guinée Construction',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=IbrahimaCamara&skinColor=brown&top=shortCurly&accessories=blank&clothingColor=2d6a4f',
    content: 'J\'ai quitté Kankan pour un chantier à Conakry grâce à une offre trouvée sur JobGuinée. Le processus de candidature est simple, même avec un téléphone basique.',
    rating: 5,
    date: '2025-12-01',
  },
  {
    id: 4,
    name: 'Aissatou Diallo',
    role: 'Assistante Administrative',
    company: 'ONG Développement Guinée',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=AissatouDiallo&skinColor=darkBrown&top=longHairStraight&accessories=blank&clothingColor=8b5cf6',
    content: 'Diplômée de l\'Université de Conakry, j\'ai trouvé mon premier emploi en 3 semaines sur JobGuinée. Les offres sont vérifiées et les entreprises répondent vraiment.',
    rating: 5,
    date: '2025-09-20',
  },
  {
    id: 5,
    name: 'Ousmane Barry',
    role: 'Électricien Industriel',
    company: 'Énergie de Guinée',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=OusmaneBarry&skinColor=brown&top=shortRound&accessories=blank&clothingColor=0e2f56',
    content: 'Après ma formation à Labé, j\'ai postulé à 3 offres sur JobGuinée et reçu 2 réponses positives. Le site est rapide même avec la connexion ici en Moyenne Guinée.',
    rating: 5,
    date: '2025-11-10',
  },
  {
    id: 6,
    name: 'Mariama Touré',
    role: 'Responsable Commerciale',
    company: 'Distribution Alimentaire GN',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=MariamToure&skinColor=darkBrown&top=longHairBob&accessories=blank&clothingColor=dc2626',
    content: 'JobGuinée est la meilleure plateforme d\'emploi en Guinée. J\'ai recruté 4 commerciaux pour notre antenne de Kindia en moins d\'un mois. Efficace et professionnel !',
    rating: 5,
    date: '2025-10-05',
  },
];

export const companies = [
  {
    id: 'comp-1',
    name: 'Mining Corp Guinée',
    logo: 'https://ui-avatars.com/api/?name=Mining+Corp&background=0E2F56&color=fff&size=200',
    activeJobs: 8,
    sector: 'Mines et Carrières',
  },
  {
    id: 'comp-2',
    name: 'Bauxite International',
    logo: 'https://ui-avatars.com/api/?name=Bauxite+Int&background=059669&color=fff&size=200',
    activeJobs: 12,
    sector: 'Mines et Carrières',
  },
  {
    id: 'comp-3',
    name: 'Digital Guinée Agency',
    logo: 'https://ui-avatars.com/api/?name=Digital+Agency&background=FF8C00&color=fff&size=200',
    activeJobs: 5,
    sector: 'Marketing & Digital',
  },
  {
    id: 'comp-4',
    name: 'TechHub Africa',
    logo: 'https://ui-avatars.com/api/?name=TechHub&background=8B5CF6&color=fff&size=200',
    activeJobs: 7,
    sector: 'Technologies',
  },
  {
    id: 'comp-5',
    name: 'Groupe Industriel Guinéen',
    logo: 'https://ui-avatars.com/api/?name=GIG&background=DC2626&color=fff&size=200',
    activeJobs: 15,
    sector: 'Industrie',
  },
  {
    id: 'comp-6',
    name: 'Finance Solutions Guinée',
    logo: 'https://ui-avatars.com/api/?name=Finance+Solutions&background=10B981&color=fff&size=200',
    activeJobs: 6,
    sector: 'Finance et Banque',
  },
  {
    id: 'comp-7',
    name: 'BTP Guinée Construction',
    logo: 'https://ui-avatars.com/api/?name=BTP+Guinee&background=F59E0B&color=fff&size=200',
    activeJobs: 10,
    sector: 'BTP et Construction',
  },
  {
    id: 'comp-8',
    name: 'Santé Plus Clinique',
    logo: 'https://ui-avatars.com/api/?name=Sante+Plus&background=EF4444&color=fff&size=200',
    activeJobs: 4,
    sector: 'Santé',
  },
];

export const jobCategories = [
  {
    id: 'cat-1',
    name: 'Mines et Carrières',
    icon: '⛏️',
    count: 45,
    color: 'from-gray-600 to-gray-800',
  },
  {
    id: 'cat-2',
    name: 'BTP et Construction',
    icon: '🏗️',
    count: 38,
    color: 'from-orange-500 to-orange-700',
  },
  {
    id: 'cat-3',
    name: 'Finance et Banque',
    icon: '💰',
    count: 29,
    color: 'from-green-500 to-green-700',
  },
  {
    id: 'cat-4',
    name: 'Ressources Humaines',
    icon: '👥',
    count: 22,
    color: 'from-blue-500 to-blue-700',
  },
  {
    id: 'cat-5',
    name: 'Technologies',
    icon: '💻',
    count: 34,
    color: 'from-purple-500 to-purple-700',
  },
  {
    id: 'cat-6',
    name: 'Santé',
    icon: '🏥',
    count: 18,
    color: 'from-red-500 to-red-700',
  },
  {
    id: 'cat-7',
    name: 'Logistique et Transport',
    icon: '🚛',
    count: 25,
    color: 'from-indigo-500 to-indigo-700',
  },
  {
    id: 'cat-8',
    name: 'Énergie',
    icon: '⚡',
    count: 16,
    color: 'from-yellow-500 to-yellow-700',
  },
];

export const guineaRegions = [
  { name: 'Conakry', jobs: 156, lat: 9.6412, lng: -13.5784 },
  { name: 'Boké', jobs: 45, lat: 10.9425, lng: -14.2917 },
  { name: 'Kamsar', jobs: 38, lat: 10.6667, lng: -14.6167 },
  { name: 'Kindia', jobs: 28, lat: 10.0667, lng: -12.85 },
  { name: 'Labé', jobs: 22, lat: 11.3167, lng: -12.2833 },
  { name: 'Nzérékoré', jobs: 19, lat: 7.75, lng: -8.8167 },
  { name: 'Kankan', jobs: 25, lat: 10.3833, lng: -9.3056 },
  { name: 'Siguiri', jobs: 31, lat: 11.4167, lng: -9.1667 },
  { name: 'Mamou', jobs: 15, lat: 10.3667, lng: -12.0833 },
  { name: 'Faranah', jobs: 12, lat: 10.0333, lng: -10.7333 },
];
